<script context="module">

    /**
     * @typedef {Object} SelectOptions
     * @property {string} value
     * @property {string} name
     * @property {string} info
    */

    /**
     * CSS Units
     * @type Array<SelectOptions>
     */
    export let cssUnitOptions = [
        {name: "TW",    value: "class", info: "Tailwind Class"},
        {name: "px",    value: "px",    info: "pixels (1px = 1/96th of 1in) "},
        {name: "em",    value: "em",    info: "Relative to the font-size of the element (2em means 2 times the size of the current font)"},
        {name: "rem",   value: "rem",   info: "Relative to font-size of the root element"},
        {name: "vw",    value: "vw",    info: "Relative to 1% of the width of the viewport"},
        {name: "vh",    value: "vh",    info: "Relative to 1% of the height of the viewport"},
        {name: "vmin",  value: "vmin",  info: "Relative to 1% of viewport's* smaller dimension"},
        {name: "vmax",  value: "vmax",  info: "Relative to 1% of viewport's* larger dimension"},
        {name: "%",     value: "%",     info: "Relative to the parent element"},
        {name: "cm",    value: "cm",    info: "centimeters"},
        {name: "mm",    value: "mm",    info: "millimeters"},
        {name: "in",    value: "in",    info: "inches (1in = 96px = 2.54cm) "},
        {name: "pt",    value: "pt",    info: "points (1pt = 1/72 of 1in) "},
        {name: "pc",    value: "pc",    info: "picas (1pc = 12 pt) "},
    ];


    /**
     * Tailwind top- classes
     * @type Array<SelectOptions>
     */
    export let topClassOptions = [

        {name: "full",  value: "top-full",  info: "top: 100%;"},
        {name: "3/4",   value: "top-3/4",   info: "top: 75%;"},
        {name: "2/4",   value: "top-2/4",   info: "top: 50%;"},
        {name: "1/4",   value: "top-1/4",   info: "top: 25%;"},
        {name: "2/3",   value: "top-2/3",   info: "top: 66.666667%;"},
        {name: "1/3",   value: "top-1/3",   info: "top: 33.333333%;"},
        {name: "1/2",   value: "top-1/2",   info: "top: 50%;"},

        {name: "96",    value: "top-96",    info: "top: 24rem; /* 384px */"},
        {name: "80",    value: "top-80",    info: "top: 20rem; /* 320px */"},
        {name: "72",    value: "top-72",    info: "top: 18rem; /* 288px */"},
        {name: "64",    value: "top-64",    info: "top: 16rem; /* 256px */"},
        {name: "60",    value: "top-60",    info: "top: 15rem; /* 240px */"},
        {name: "56",    value: "top-56",    info: "top: 14rem; /* 224px */"},
        {name: "52",    value: "top-52",    info: "top: 13rem; /* 208px */"},
        {name: "48",    value: "top-48",    info: "top: 12rem; /* 192px */"},
        {name: "44",    value: "top-44",    info: "top: 11rem; /* 176px */"},
        {name: "40",    value: "top-40",    info: "top: 10rem; /* 160px */"},
        {name: "36",    value: "top-36",    info: "top: 9rem; /* 144px */"},
        {name: "32",    value: "top-32",    info: "top: 8rem; /* 128px */"},
        {name: "28",    value: "top-28",    info: "top: 7rem; /* 112px */"},
        {name: "24",    value: "top-24",    info: "top: 6rem; /* 96px */"},
        {name: "20",    value: "top-20",    info: "top: 5rem; /* 80px */"},
        {name: "16",    value: "top-16",    info: "top: 4rem; /* 64px */"},
        {name: "14",    value: "top-14",    info: "top: 3.5rem; /* 56px */"},
        {name: "12",    value: "top-12",    info: "top: 3rem; /* 48px */"},
        {name: "11",    value: "top-11",    info: "top: 2.75rem; /* 44px */"},
        {name: "10",    value: "top-10",    info: "top: 2.5rem; /* 40px */"},
        {name: "9",     value: "top-9",     info: "top: 2.25rem; /* 36px */"},
        {name: "8",     value: "top-8",     info: "top: 2rem; /* 32px */"},
        {name: "7",     value: "top-7",     info: "top: 1.75rem; /* 28px */"},
        {name: "6",     value: "top-6",     info: "top: 1.5rem; /* 24px */"},
        {name: "5",     value: "top-5",     info: "top: 1.25rem; /* 20px */"},
        {name: "4",     value: "top-4",     info: "top: 1rem; /* 16px */"},
        {name: "3.5",   value: "top-3.5",   info: "top: 0.875rem; /* 14px */"},
        {name: "3",     value: "top-3",     info: "top: 0.75rem; /* 12px */"},
        {name: "2.5",   value: "top-2.5",   info: "top: 0.625rem; /* 10px */"},
        {name: "2",     value: "top-2",     info: "top: 0.5rem; /* 8px */"},
        {name: "1.5",   value: "top-1.5",   info: "top: 0.375rem; /* 6px */"},
        {name: "1",     value: "top-1",     info: "top: 0.25rem; /* 4px */"},
        {name: "0.5",   value: "top-0.5",   info: "top: 0.125rem; /* 2px */"},
        {name: "px",    value: "top-px",    info: "top: 1px;"},

        {name: "-",     value: "",          info: "Default - No value"},
        {name: "0",     value: "top-0",     info: "top: 0px;"},

        {name: "-px",    value: "-top-px",    info: "top: -1px;"},
        {name: "-0.5",   value: "-top-0.5",   info: "top: -0.125rem; /* -2px */"},
        {name: "-1",     value: "-top-1",     info: "top: -0.25rem; /* -4px */"},
        {name: "-1.5",   value: "-top-1.5",   info: "top: -0.375rem; /* -6px */"},
        {name: "-2",     value: "-top-2",     info: "top: -0.5rem; /* -8px */"},
        {name: "-2.5",   value: "-top-2.5",   info: "top: -0.625rem; /* -10px */"},
        {name: "-3",     value: "-top-3",     info: "top: -0.75rem; /* -12px */"},
        {name: "-3.5",   value: "-top-3.5",   info: "top: -0.875rem; /* -14px */"},
        {name: "-4",     value: "-top-4",     info: "top: -1rem; /* -16px */"},
        {name: "-5",     value: "-top-5",     info: "top: -1.25rem; /* -20px */"},
        {name: "-6",     value: "-top-6",     info: "top: -1.5rem; /* -24px */"},
        {name: "-7",     value: "-top-7",     info: "top: -1.75rem; /* -28px */"},
        {name: "-8",     value: "-top-8",     info: "top: -2rem; /* -32px */"},
        {name: "-9",     value: "-top-9",     info: "top: -2.25rem; /* -36px */"},
        {name: "-10",    value: "-top-10",    info: "top: -2.5rem; /* -40px */"},
        {name: "-11",    value: "-top-11",    info: "top: -2.75rem; /* -44px */"},
        {name: "-12",    value: "-top-12",    info: "top: -3rem; /* -48px */"},
        {name: "-14",    value: "-top-14",    info: "top: -3.5rem; /* -56px */"},
        {name: "-16",    value: "-top-16",    info: "top: -4rem; /* -64px */"},
        {name: "-20",    value: "-top-20",    info: "top: -5rem; /* -80px */"},
        {name: "-24",    value: "-top-24",    info: "top: -6rem; /* -96px */"},
        {name: "-28",    value: "-top-28",    info: "top: -7rem; /* -112px */"},
        {name: "-32",    value: "-top-32",    info: "top: -8rem; /* -128px */"},
        {name: "-36",    value: "-top-36",    info: "top: -9rem; /* -144px */"},
        {name: "-40",    value: "-top-40",    info: "top: -10rem; /* -160px */"},
        {name: "-44",    value: "-top-44",    info: "top: -11rem; /* -176px */"},
        {name: "-48",    value: "-top-48",    info: "top: -12rem; /* -192px */"},
        {name: "-52",    value: "-top-52",    info: "top: -13rem; /* -208px */"},
        {name: "-56",    value: "-top-56",    info: "top: -14rem; /* -224px */"},
        {name: "-60",    value: "-top-60",    info: "top: -15rem; /* -240px */"},
        {name: "-64",    value: "-top-64",    info: "top: -16rem; /* -256px */"},
        {name: "-72",    value: "-top-72",    info: "top: -18rem; /* -288px */"},
        {name: "-80",    value: "-top-80",    info: "top: -20rem; /* -320px */"},
        {name: "-96",    value: "-top-96",    info: "top: -24rem; /* -384px */"},

        {name: "-auto",  value: "-top-auto",  info: "top: -auto;"},
        {name: "-1/2",   value: "-top-1/2",   info: "top: -50%;"},
        {name: "-1/3",   value: "-top-1/3",   info: "top: -33.333333%;"},
        {name: "-2/3",   value: "-top-2/3",   info: "top: -66.666667%;"},
        {name: "-1/4",   value: "-top-1/4",   info: "top: -25%;"},
        {name: "-2/4",   value: "-top-2/4",   info: "top: -50%;"},
        {name: "-3/4",   value: "-top-3/4",   info: "top: -75%;"},
        {name: "-full",  value: "-top-full",  info: "top: -100%;"},

    ];

    /**
     * Tailwind right- classes
     * @type Array<SelectOptions>
     */
    export let rightClassOptions = [
        {name: "full",  value: "right-full",  info: "right: 100%;"},
        {name: "3/4",   value: "right-3/4",   info: "right: 75%;"},
        {name: "2/4",   value: "right-2/4",   info: "right: 50%;"},
        {name: "1/4",   value: "right-1/4",   info: "right: 25%;"},
        {name: "2/3",   value: "right-2/3",   info: "right: 66.666667%;"},
        {name: "1/3",   value: "right-1/3",   info: "right: 33.333333%;"},
        {name: "1/2",   value: "right-1/2",   info: "right: 50%;"},

        {name: "96",    value: "right-96",    info: "right: 24rem; /* 384px */"},
        {name: "80",    value: "right-80",    info: "right: 20rem; /* 320px */"},
        {name: "72",    value: "right-72",    info: "right: 18rem; /* 288px */"},
        {name: "64",    value: "right-64",    info: "right: 16rem; /* 256px */"},
        {name: "60",    value: "right-60",    info: "right: 15rem; /* 240px */"},
        {name: "56",    value: "right-56",    info: "right: 14rem; /* 224px */"},
        {name: "52",    value: "right-52",    info: "right: 13rem; /* 208px */"},
        {name: "48",    value: "right-48",    info: "right: 12rem; /* 192px */"},
        {name: "44",    value: "right-44",    info: "right: 11rem; /* 176px */"},
        {name: "40",    value: "right-40",    info: "right: 10rem; /* 160px */"},
        {name: "36",    value: "right-36",    info: "right: 9rem; /* 144px */"},
        {name: "32",    value: "right-32",    info: "right: 8rem; /* 128px */"},
        {name: "28",    value: "right-28",    info: "right: 7rem; /* 112px */"},
        {name: "24",    value: "right-24",    info: "right: 6rem; /* 96px */"},
        {name: "20",    value: "right-20",    info: "right: 5rem; /* 80px */"},
        {name: "16",    value: "right-16",    info: "right: 4rem; /* 64px */"},
        {name: "14",    value: "right-14",    info: "right: 3.5rem; /* 56px */"},
        {name: "12",    value: "right-12",    info: "right: 3rem; /* 48px */"},
        {name: "11",    value: "right-11",    info: "right: 2.75rem; /* 44px */"},
        {name: "10",    value: "right-10",    info: "right: 2.5rem; /* 40px */"},
        {name: "9",     value: "right-9",     info: "right: 2.25rem; /* 36px */"},
        {name: "8",     value: "right-8",     info: "right: 2rem; /* 32px */"},
        {name: "7",     value: "right-7",     info: "right: 1.75rem; /* 28px */"},
        {name: "6",     value: "right-6",     info: "right: 1.5rem; /* 24px */"},
        {name: "5",     value: "right-5",     info: "right: 1.25rem; /* 20px */"},
        {name: "4",     value: "right-4",     info: "right: 1rem; /* 16px */"},
        {name: "3.5",   value: "right-3.5",   info: "right: 0.875rem; /* 14px */"},
        {name: "3",     value: "right-3",     info: "right: 0.75rem; /* 12px */"},
        {name: "2.5",   value: "right-2.5",   info: "right: 0.625rem; /* 10px */"},
        {name: "2",     value: "right-2",     info: "right: 0.5rem; /* 8px */"},
        {name: "1.5",   value: "right-1.5",   info: "right: 0.375rem; /* 6px */"},
        {name: "1",     value: "right-1",     info: "right: 0.25rem; /* 4px */"},
        {name: "0.5",   value: "right-0.5",   info: "right: 0.125rem; /* 2px */"},
        {name: "px",    value: "right-px",    info: "right: 1px;"},

        {name: "-",     value: "",          info: "Default - No value"},
        {name: "0",     value: "right-0",     info: "right: 0px;"},

        {name: "-px",    value: "-right-px",    info: "right: -1px;"},
        {name: "-0.5",   value: "-right-0.5",   info: "right: -0.125rem; /* -2px */"},
        {name: "-1",     value: "-right-1",     info: "right: -0.25rem; /* -4px */"},
        {name: "-1.5",   value: "-right-1.5",   info: "right: -0.375rem; /* -6px */"},
        {name: "-2",     value: "-right-2",     info: "right: -0.5rem; /* -8px */"},
        {name: "-2.5",   value: "-right-2.5",   info: "right: -0.625rem; /* -10px */"},
        {name: "-3",     value: "-right-3",     info: "right: -0.75rem; /* -12px */"},
        {name: "-3.5",   value: "-right-3.5",   info: "right: -0.875rem; /* -14px */"},
        {name: "-4",     value: "-right-4",     info: "right: -1rem; /* -16px */"},
        {name: "-5",     value: "-right-5",     info: "right: -1.25rem; /* -20px */"},
        {name: "-6",     value: "-right-6",     info: "right: -1.5rem; /* -24px */"},
        {name: "-7",     value: "-right-7",     info: "right: -1.75rem; /* -28px */"},
        {name: "-8",     value: "-right-8",     info: "right: -2rem; /* -32px */"},
        {name: "-9",     value: "-right-9",     info: "right: -2.25rem; /* -36px */"},
        {name: "-10",    value: "-right-10",    info: "right: -2.5rem; /* -40px */"},
        {name: "-11",    value: "-right-11",    info: "right: -2.75rem; /* -44px */"},
        {name: "-12",    value: "-right-12",    info: "right: -3rem; /* -48px */"},
        {name: "-14",    value: "-right-14",    info: "right: -3.5rem; /* -56px */"},
        {name: "-16",    value: "-right-16",    info: "right: -4rem; /* -64px */"},
        {name: "-20",    value: "-right-20",    info: "right: -5rem; /* -80px */"},
        {name: "-24",    value: "-right-24",    info: "right: -6rem; /* -96px */"},
        {name: "-28",    value: "-right-28",    info: "right: -7rem; /* -112px */"},
        {name: "-32",    value: "-right-32",    info: "right: -8rem; /* -128px */"},
        {name: "-36",    value: "-right-36",    info: "right: -9rem; /* -144px */"},
        {name: "-40",    value: "-right-40",    info: "right: -10rem; /* -160px */"},
        {name: "-44",    value: "-right-44",    info: "right: -11rem; /* -176px */"},
        {name: "-48",    value: "-right-48",    info: "right: -12rem; /* -192px */"},
        {name: "-52",    value: "-right-52",    info: "right: -13rem; /* -208px */"},
        {name: "-56",    value: "-right-56",    info: "right: -14rem; /* -224px */"},
        {name: "-60",    value: "-right-60",    info: "right: -15rem; /* -240px */"},
        {name: "-64",    value: "-right-64",    info: "right: -16rem; /* -256px */"},
        {name: "-72",    value: "-right-72",    info: "right: -18rem; /* -288px */"},
        {name: "-80",    value: "-right-80",    info: "right: -20rem; /* -320px */"},
        {name: "-96",    value: "-right-96",    info: "right: -24rem; /* -384px */"},

        {name: "-auto",  value: "-right-auto",  info: "right: -auto;"},
        {name: "-1/2",   value: "-right-1/2",   info: "right: -50%;"},
        {name: "-1/3",   value: "-right-1/3",   info: "right: -33.333333%;"},
        {name: "-2/3",   value: "-right-2/3",   info: "right: -66.666667%;"},
        {name: "-1/4",   value: "-right-1/4",   info: "right: -25%;"},
        {name: "-2/4",   value: "-right-2/4",   info: "right: -50%;"},
        {name: "-3/4",   value: "-right-3/4",   info: "right: -75%;"},
        {name: "-full",  value: "-right-full",  info: "right: -100%;"},
    ];

    /**
     * Tailwind bottom- classes
     * @type Array<SelectOptions>
     */
    export let bottomClassOptions = [
        {name: "full",  value: "bottom-full",  info: "bottom: 100%;"},
        {name: "3/4",   value: "bottom-3/4",   info: "bottom: 75%;"},
        {name: "2/4",   value: "bottom-2/4",   info: "bottom: 50%;"},
        {name: "1/4",   value: "bottom-1/4",   info: "bottom: 25%;"},
        {name: "2/3",   value: "bottom-2/3",   info: "bottom: 66.666667%;"},
        {name: "1/3",   value: "bottom-1/3",   info: "bottom: 33.333333%;"},
        {name: "1/2",   value: "bottom-1/2",   info: "bottom: 50%;"},

        {name: "96",    value: "bottom-96",    info: "bottom: 24rem; /* 384px */"},
        {name: "80",    value: "bottom-80",    info: "bottom: 20rem; /* 320px */"},
        {name: "72",    value: "bottom-72",    info: "bottom: 18rem; /* 288px */"},
        {name: "64",    value: "bottom-64",    info: "bottom: 16rem; /* 256px */"},
        {name: "60",    value: "bottom-60",    info: "bottom: 15rem; /* 240px */"},
        {name: "56",    value: "bottom-56",    info: "bottom: 14rem; /* 224px */"},
        {name: "52",    value: "bottom-52",    info: "bottom: 13rem; /* 208px */"},
        {name: "48",    value: "bottom-48",    info: "bottom: 12rem; /* 192px */"},
        {name: "44",    value: "bottom-44",    info: "bottom: 11rem; /* 176px */"},
        {name: "40",    value: "bottom-40",    info: "bottom: 10rem; /* 160px */"},
        {name: "36",    value: "bottom-36",    info: "bottom: 9rem; /* 144px */"},
        {name: "32",    value: "bottom-32",    info: "bottom: 8rem; /* 128px */"},
        {name: "28",    value: "bottom-28",    info: "bottom: 7rem; /* 112px */"},
        {name: "24",    value: "bottom-24",    info: "bottom: 6rem; /* 96px */"},
        {name: "20",    value: "bottom-20",    info: "bottom: 5rem; /* 80px */"},
        {name: "16",    value: "bottom-16",    info: "bottom: 4rem; /* 64px */"},
        {name: "14",    value: "bottom-14",    info: "bottom: 3.5rem; /* 56px */"},
        {name: "12",    value: "bottom-12",    info: "bottom: 3rem; /* 48px */"},
        {name: "11",    value: "bottom-11",    info: "bottom: 2.75rem; /* 44px */"},
        {name: "10",    value: "bottom-10",    info: "bottom: 2.5rem; /* 40px */"},
        {name: "9",     value: "bottom-9",     info: "bottom: 2.25rem; /* 36px */"},
        {name: "8",     value: "bottom-8",     info: "bottom: 2rem; /* 32px */"},
        {name: "7",     value: "bottom-7",     info: "bottom: 1.75rem; /* 28px */"},
        {name: "6",     value: "bottom-6",     info: "bottom: 1.5rem; /* 24px */"},
        {name: "5",     value: "bottom-5",     info: "bottom: 1.25rem; /* 20px */"},
        {name: "4",     value: "bottom-4",     info: "bottom: 1rem; /* 16px */"},
        {name: "3.5",   value: "bottom-3.5",   info: "bottom: 0.875rem; /* 14px */"},
        {name: "3",     value: "bottom-3",     info: "bottom: 0.75rem; /* 12px */"},
        {name: "2.5",   value: "bottom-2.5",   info: "bottom: 0.625rem; /* 10px */"},
        {name: "2",     value: "bottom-2",     info: "bottom: 0.5rem; /* 8px */"},
        {name: "1.5",   value: "bottom-1.5",   info: "bottom: 0.375rem; /* 6px */"},
        {name: "1",     value: "bottom-1",     info: "bottom: 0.25rem; /* 4px */"},
        {name: "0.5",   value: "bottom-0.5",   info: "bottom: 0.125rem; /* 2px */"},
        {name: "px",    value: "bottom-px",    info: "bottom: 1px;"},

        {name: "-",     value: "",          info: "Default - No value"},
        {name: "0",     value: "bottom-0",     info: "bottom: 0px;"},

        {name: "-px",    value: "-bottom-px",    info: "bottom: -1px;"},
        {name: "-0.5",   value: "-bottom-0.5",   info: "bottom: -0.125rem; /* -2px */"},
        {name: "-1",     value: "-bottom-1",     info: "bottom: -0.25rem; /* -4px */"},
        {name: "-1.5",   value: "-bottom-1.5",   info: "bottom: -0.375rem; /* -6px */"},
        {name: "-2",     value: "-bottom-2",     info: "bottom: -0.5rem; /* -8px */"},
        {name: "-2.5",   value: "-bottom-2.5",   info: "bottom: -0.625rem; /* -10px */"},
        {name: "-3",     value: "-bottom-3",     info: "bottom: -0.75rem; /* -12px */"},
        {name: "-3.5",   value: "-bottom-3.5",   info: "bottom: -0.875rem; /* -14px */"},
        {name: "-4",     value: "-bottom-4",     info: "bottom: -1rem; /* -16px */"},
        {name: "-5",     value: "-bottom-5",     info: "bottom: -1.25rem; /* -20px */"},
        {name: "-6",     value: "-bottom-6",     info: "bottom: -1.5rem; /* -24px */"},
        {name: "-7",     value: "-bottom-7",     info: "bottom: -1.75rem; /* -28px */"},
        {name: "-8",     value: "-bottom-8",     info: "bottom: -2rem; /* -32px */"},
        {name: "-9",     value: "-bottom-9",     info: "bottom: -2.25rem; /* -36px */"},
        {name: "-10",    value: "-bottom-10",    info: "bottom: -2.5rem; /* -40px */"},
        {name: "-11",    value: "-bottom-11",    info: "bottom: -2.75rem; /* -44px */"},
        {name: "-12",    value: "-bottom-12",    info: "bottom: -3rem; /* -48px */"},
        {name: "-14",    value: "-bottom-14",    info: "bottom: -3.5rem; /* -56px */"},
        {name: "-16",    value: "-bottom-16",    info: "bottom: -4rem; /* -64px */"},
        {name: "-20",    value: "-bottom-20",    info: "bottom: -5rem; /* -80px */"},
        {name: "-24",    value: "-bottom-24",    info: "bottom: -6rem; /* -96px */"},
        {name: "-28",    value: "-bottom-28",    info: "bottom: -7rem; /* -112px */"},
        {name: "-32",    value: "-bottom-32",    info: "bottom: -8rem; /* -128px */"},
        {name: "-36",    value: "-bottom-36",    info: "bottom: -9rem; /* -144px */"},
        {name: "-40",    value: "-bottom-40",    info: "bottom: -10rem; /* -160px */"},
        {name: "-44",    value: "-bottom-44",    info: "bottom: -11rem; /* -176px */"},
        {name: "-48",    value: "-bottom-48",    info: "bottom: -12rem; /* -192px */"},
        {name: "-52",    value: "-bottom-52",    info: "bottom: -13rem; /* -208px */"},
        {name: "-56",    value: "-bottom-56",    info: "bottom: -14rem; /* -224px */"},
        {name: "-60",    value: "-bottom-60",    info: "bottom: -15rem; /* -240px */"},
        {name: "-64",    value: "-bottom-64",    info: "bottom: -16rem; /* -256px */"},
        {name: "-72",    value: "-bottom-72",    info: "bottom: -18rem; /* -288px */"},
        {name: "-80",    value: "-bottom-80",    info: "bottom: -20rem; /* -320px */"},
        {name: "-96",    value: "-bottom-96",    info: "bottom: -24rem; /* -384px */"},

        {name: "-auto",  value: "-bottom-auto",  info: "bottom: -auto;"},
        {name: "-1/2",   value: "-bottom-1/2",   info: "bottom: -50%;"},
        {name: "-1/3",   value: "-bottom-1/3",   info: "bottom: -33.333333%;"},
        {name: "-2/3",   value: "-bottom-2/3",   info: "bottom: -66.666667%;"},
        {name: "-1/4",   value: "-bottom-1/4",   info: "bottom: -25%;"},
        {name: "-2/4",   value: "-bottom-2/4",   info: "bottom: -50%;"},
        {name: "-3/4",   value: "-bottom-3/4",   info: "bottom: -75%;"},
        {name: "-full",  value: "-bottom-full",  info: "bottom: -100%;"},
    ];

    /**
     * Tailwind left- classes
     * @type Array<SelectOptions>
     */
    export let leftClassOptions = [
        {name: "full",  value: "left-full",  info: "left: 100%;"},
        {name: "3/4",   value: "left-3/4",   info: "left: 75%;"},
        {name: "2/4",   value: "left-2/4",   info: "left: 50%;"},
        {name: "1/4",   value: "left-1/4",   info: "left: 25%;"},
        {name: "2/3",   value: "left-2/3",   info: "left: 66.666667%;"},
        {name: "1/3",   value: "left-1/3",   info: "left: 33.333333%;"},
        {name: "1/2",   value: "left-1/2",   info: "left: 50%;"},

        {name: "96",    value: "left-96",    info: "left: 24rem; /* 384px */"},
        {name: "80",    value: "left-80",    info: "left: 20rem; /* 320px */"},
        {name: "72",    value: "left-72",    info: "left: 18rem; /* 288px */"},
        {name: "64",    value: "left-64",    info: "left: 16rem; /* 256px */"},
        {name: "60",    value: "left-60",    info: "left: 15rem; /* 240px */"},
        {name: "56",    value: "left-56",    info: "left: 14rem; /* 224px */"},
        {name: "52",    value: "left-52",    info: "left: 13rem; /* 208px */"},
        {name: "48",    value: "left-48",    info: "left: 12rem; /* 192px */"},
        {name: "44",    value: "left-44",    info: "left: 11rem; /* 176px */"},
        {name: "40",    value: "left-40",    info: "left: 10rem; /* 160px */"},
        {name: "36",    value: "left-36",    info: "left: 9rem; /* 144px */"},
        {name: "32",    value: "left-32",    info: "left: 8rem; /* 128px */"},
        {name: "28",    value: "left-28",    info: "left: 7rem; /* 112px */"},
        {name: "24",    value: "left-24",    info: "left: 6rem; /* 96px */"},
        {name: "20",    value: "left-20",    info: "left: 5rem; /* 80px */"},
        {name: "16",    value: "left-16",    info: "left: 4rem; /* 64px */"},
        {name: "14",    value: "left-14",    info: "left: 3.5rem; /* 56px */"},
        {name: "12",    value: "left-12",    info: "left: 3rem; /* 48px */"},
        {name: "11",    value: "left-11",    info: "left: 2.75rem; /* 44px */"},
        {name: "10",    value: "left-10",    info: "left: 2.5rem; /* 40px */"},
        {name: "9",     value: "left-9",     info: "left: 2.25rem; /* 36px */"},
        {name: "8",     value: "left-8",     info: "left: 2rem; /* 32px */"},
        {name: "7",     value: "left-7",     info: "left: 1.75rem; /* 28px */"},
        {name: "6",     value: "left-6",     info: "left: 1.5rem; /* 24px */"},
        {name: "5",     value: "left-5",     info: "left: 1.25rem; /* 20px */"},
        {name: "4",     value: "left-4",     info: "left: 1rem; /* 16px */"},
        {name: "3.5",   value: "left-3.5",   info: "left: 0.875rem; /* 14px */"},
        {name: "3",     value: "left-3",     info: "left: 0.75rem; /* 12px */"},
        {name: "2.5",   value: "left-2.5",   info: "left: 0.625rem; /* 10px */"},
        {name: "2",     value: "left-2",     info: "left: 0.5rem; /* 8px */"},
        {name: "1.5",   value: "left-1.5",   info: "left: 0.375rem; /* 6px */"},
        {name: "1",     value: "left-1",     info: "left: 0.25rem; /* 4px */"},
        {name: "0.5",   value: "left-0.5",   info: "left: 0.125rem; /* 2px */"},
        {name: "px",    value: "left-px",    info: "left: 1px;"},

        {name: "-",     value: "",          info: "Default - No value"},
        {name: "0",     value: "left-0",     info: "left: 0px;"},

        {name: "-px",    value: "-left-px",    info: "left: -1px;"},
        {name: "-0.5",   value: "-left-0.5",   info: "left: -0.125rem; /* -2px */"},
        {name: "-1",     value: "-left-1",     info: "left: -0.25rem; /* -4px */"},
        {name: "-1.5",   value: "-left-1.5",   info: "left: -0.375rem; /* -6px */"},
        {name: "-2",     value: "-left-2",     info: "left: -0.5rem; /* -8px */"},
        {name: "-2.5",   value: "-left-2.5",   info: "left: -0.625rem; /* -10px */"},
        {name: "-3",     value: "-left-3",     info: "left: -0.75rem; /* -12px */"},
        {name: "-3.5",   value: "-left-3.5",   info: "left: -0.875rem; /* -14px */"},
        {name: "-4",     value: "-left-4",     info: "left: -1rem; /* -16px */"},
        {name: "-5",     value: "-left-5",     info: "left: -1.25rem; /* -20px */"},
        {name: "-6",     value: "-left-6",     info: "left: -1.5rem; /* -24px */"},
        {name: "-7",     value: "-left-7",     info: "left: -1.75rem; /* -28px */"},
        {name: "-8",     value: "-left-8",     info: "left: -2rem; /* -32px */"},
        {name: "-9",     value: "-left-9",     info: "left: -2.25rem; /* -36px */"},
        {name: "-10",    value: "-left-10",    info: "left: -2.5rem; /* -40px */"},
        {name: "-11",    value: "-left-11",    info: "left: -2.75rem; /* -44px */"},
        {name: "-12",    value: "-left-12",    info: "left: -3rem; /* -48px */"},
        {name: "-14",    value: "-left-14",    info: "left: -3.5rem; /* -56px */"},
        {name: "-16",    value: "-left-16",    info: "left: -4rem; /* -64px */"},
        {name: "-20",    value: "-left-20",    info: "left: -5rem; /* -80px */"},
        {name: "-24",    value: "-left-24",    info: "left: -6rem; /* -96px */"},
        {name: "-28",    value: "-left-28",    info: "left: -7rem; /* -112px */"},
        {name: "-32",    value: "-left-32",    info: "left: -8rem; /* -128px */"},
        {name: "-36",    value: "-left-36",    info: "left: -9rem; /* -144px */"},
        {name: "-40",    value: "-left-40",    info: "left: -10rem; /* -160px */"},
        {name: "-44",    value: "-left-44",    info: "left: -11rem; /* -176px */"},
        {name: "-48",    value: "-left-48",    info: "left: -12rem; /* -192px */"},
        {name: "-52",    value: "-left-52",    info: "left: -13rem; /* -208px */"},
        {name: "-56",    value: "-left-56",    info: "left: -14rem; /* -224px */"},
        {name: "-60",    value: "-left-60",    info: "left: -15rem; /* -240px */"},
        {name: "-64",    value: "-left-64",    info: "left: -16rem; /* -256px */"},
        {name: "-72",    value: "-left-72",    info: "left: -18rem; /* -288px */"},
        {name: "-80",    value: "-left-80",    info: "left: -20rem; /* -320px */"},
        {name: "-96",    value: "-left-96",    info: "left: -24rem; /* -384px */"},

        {name: "-auto",  value: "-left-auto",  info: "left: -auto;"},
        {name: "-1/2",   value: "-left-1/2",   info: "left: -50%;"},
        {name: "-1/3",   value: "-left-1/3",   info: "left: -33.333333%;"},
        {name: "-2/3",   value: "-left-2/3",   info: "left: -66.666667%;"},
        {name: "-1/4",   value: "-left-1/4",   info: "left: -25%;"},
        {name: "-2/4",   value: "-left-2/4",   info: "left: -50%;"},
        {name: "-3/4",   value: "-left-3/4",   info: "left: -75%;"},
        {name: "-full",  value: "-left-full",  info: "left: -100%;"},
    ];


    /**
     * Tailwind Padding Left classes
     * @type Array<SelectOptions>
     */
    export let paddingLeftClassOptions = [

        {name: "96",    value: "pl-96",    info: "padding-left: 24rem; /* 384px */"},
        {name: "80",    value: "pl-80",    info: "padding-left: 20rem; /* 320px */"},
        {name: "72",    value: "pl-72",    info: "padding-left: 18rem; /* 288px */"},
        {name: "64",    value: "pl-64",    info: "padding-left: 16rem; /* 256px */"},
        {name: "60",    value: "pl-60",    info: "padding-left: 15rem; /* 240px */"},
        {name: "56",    value: "pl-56",    info: "padding-left: 14rem; /* 224px */"},
        {name: "52",    value: "pl-52",    info: "padding-left: 13rem; /* 208px */"},
        {name: "48",    value: "pl-48",    info: "padding-left: 12rem; /* 192px */"},
        {name: "44",    value: "pl-44",    info: "padding-left: 11rem; /* 176px */"},
        {name: "40",    value: "pl-40",    info: "padding-left: 10rem; /* 160px */"},
        {name: "36",    value: "pl-36",    info: "padding-left: 9rem; /* 144px */"},
        {name: "32",    value: "pl-32",    info: "padding-left: 8rem; /* 128px */"},
        {name: "28",    value: "pl-28",    info: "padding-left: 7rem; /* 112px */"},
        {name: "24",    value: "pl-24",    info: "padding-left: 6rem; /* 96px */"},
        {name: "20",    value: "pl-20",    info: "padding-left: 5rem; /* 80px */"},
        {name: "16",    value: "pl-16",    info: "padding-left: 4rem; /* 64px */"},
        {name: "14",    value: "pl-14",    info: "padding-left: 3.5rem; /* 56px */"},
        {name: "12",    value: "pl-12",    info: "padding-left: 3rem; /* 48px */"},
        {name: "11",    value: "pl-11",    info: "padding-left: 2.75rem; /* 44px */"},
        {name: "10",    value: "pl-10",    info: "padding-left: 2.5rem; /* 40px */"},
        {name: "9",     value: "pl-9",     info: "padding-left: 2.25rem; /* 36px */"},
        {name: "8",     value: "pl-8",     info: "padding-left: 2rem; /* 32px */"},
        {name: "7",     value: "pl-7",     info: "padding-left: 1.75rem; /* 28px */"},
        {name: "6",     value: "pl-6",     info: "padding-left: 1.5rem; /* 24px */"},
        {name: "5",     value: "pl-5",     info: "padding-left: 1.25rem; /* 20px */"},
        {name: "4",     value: "pl-4",     info: "padding-left: 1rem; /* 16px */"},
        {name: "3.5",   value: "pl-3.5",   info: "padding-left: 0.875rem; /* 14px */"},
        {name: "3",     value: "pl-3",     info: "padding-left: 0.75rem; /* 12px */"},
        {name: "2.5",   value: "pl-2.5",   info: "padding-left: 0.625rem; /* 10px */"},
        {name: "2",     value: "pl-2",     info: "padding-left: 0.5rem; /* 8px */"},
        {name: "1.5",   value: "pl-1.5",   info: "padding-left: 0.375rem; /* 6px */"},
        {name: "1",     value: "pl-1",     info: "padding-left: 0.25rem; /* 4px */"},
        {name: "0.5",   value: "pl-0.5",   info: "padding-left: 0.125rem; /* 2px */"},
        {name: "px",    value: "pl-px",    info: "padding-left: 1px;"},

        {name: "-",     value: "",         info: "Default - No value"},
        {name: "0",     value: "pl-0",     info: "padding-left: 0px;"},
    ];

    /**
     * Tailwind Padding Left classes
     * @type Array<SelectOptions>
     */
    export let paddingRightClassOptions = [
        {name: "96",    value: "pr-96",    info: "padding-right: 24rem; /* 384px */"},
        {name: "80",    value: "pr-80",    info: "padding-right: 20rem; /* 320px */"},
        {name: "72",    value: "pr-72",    info: "padding-right: 18rem; /* 288px */"},
        {name: "64",    value: "pr-64",    info: "padding-right: 16rem; /* 256px */"},
        {name: "60",    value: "pr-60",    info: "padding-right: 15rem; /* 240px */"},
        {name: "56",    value: "pr-56",    info: "padding-right: 14rem; /* 224px */"},
        {name: "52",    value: "pr-52",    info: "padding-right: 13rem; /* 208px */"},
        {name: "48",    value: "pr-48",    info: "padding-right: 12rem; /* 192px */"},
        {name: "44",    value: "pr-44",    info: "padding-right: 11rem; /* 176px */"},
        {name: "40",    value: "pr-40",    info: "padding-right: 10rem; /* 160px */"},
        {name: "36",    value: "pr-36",    info: "padding-right: 9rem; /* 144px */"},
        {name: "32",    value: "pr-32",    info: "padding-right: 8rem; /* 128px */"},
        {name: "28",    value: "pr-28",    info: "padding-right: 7rem; /* 112px */"},
        {name: "24",    value: "pr-24",    info: "padding-right: 6rem; /* 96px */"},
        {name: "20",    value: "pr-20",    info: "padding-right: 5rem; /* 80px */"},
        {name: "16",    value: "pr-16",    info: "padding-right: 4rem; /* 64px */"},
        {name: "14",    value: "pr-14",    info: "padding-right: 3.5rem; /* 56px */"},
        {name: "12",    value: "pr-12",    info: "padding-right: 3rem; /* 48px */"},
        {name: "11",    value: "pr-11",    info: "padding-right: 2.75rem; /* 44px */"},
        {name: "10",    value: "pr-10",    info: "padding-right: 2.5rem; /* 40px */"},
        {name: "9",     value: "pr-9",     info: "padding-right: 2.25rem; /* 36px */"},
        {name: "8",     value: "pr-8",     info: "padding-right: 2rem; /* 32px */"},
        {name: "7",     value: "pr-7",     info: "padding-right: 1.75rem; /* 28px */"},
        {name: "6",     value: "pr-6",     info: "padding-right: 1.5rem; /* 24px */"},
        {name: "5",     value: "pr-5",     info: "padding-right: 1.25rem; /* 20px */"},
        {name: "4",     value: "pr-4",     info: "padding-right: 1rem; /* 16px */"},
        {name: "3.5",   value: "pr-3.5",   info: "padding-right: 0.875rem; /* 14px */"},
        {name: "3",     value: "pr-3",     info: "padding-right: 0.75rem; /* 12px */"},
        {name: "2.5",   value: "pr-2.5",   info: "padding-right: 0.625rem; /* 10px */"},
        {name: "2",     value: "pr-2",     info: "padding-right: 0.5rem; /* 8px */"},
        {name: "1.5",   value: "pr-1.5",   info: "padding-right: 0.375rem; /* 6px */"},
        {name: "1",     value: "pr-1",     info: "padding-right: 0.25rem; /* 4px */"},
        {name: "0.5",   value: "pr-0.5",   info: "padding-right: 0.125rem; /* 2px */"},
        {name: "px",    value: "pr-px",    info: "padding-right: 1px;"},

        {name: "-",     value: "",          info: "Default - No value"},
        {name: "0",     value: "pr-0",     info: "padding-right: 0px;"},

    ];

    /**
     * Tailwind Padding Left classes
     * @type Array<SelectOptions>
     */
    export let paddingTopClassOptions = [
        {name: "96",    value: "pt-96",    info: "padding-top: 24rem; /* 384px */"},
        {name: "80",    value: "pt-80",    info: "padding-top: 20rem; /* 320px */"},
        {name: "72",    value: "pt-72",    info: "padding-top: 18rem; /* 288px */"},
        {name: "64",    value: "pt-64",    info: "padding-top: 16rem; /* 256px */"},
        {name: "60",    value: "pt-60",    info: "padding-top: 15rem; /* 240px */"},
        {name: "56",    value: "pt-56",    info: "padding-top: 14rem; /* 224px */"},
        {name: "52",    value: "pt-52",    info: "padding-top: 13rem; /* 208px */"},
        {name: "48",    value: "pt-48",    info: "padding-top: 12rem; /* 192px */"},
        {name: "44",    value: "pt-44",    info: "padding-top: 11rem; /* 176px */"},
        {name: "40",    value: "pt-40",    info: "padding-top: 10rem; /* 160px */"},
        {name: "36",    value: "pt-36",    info: "padding-top: 9rem; /* 144px */"},
        {name: "32",    value: "pt-32",    info: "padding-top: 8rem; /* 128px */"},
        {name: "28",    value: "pt-28",    info: "padding-top: 7rem; /* 112px */"},
        {name: "24",    value: "pt-24",    info: "padding-top: 6rem; /* 96px */"},
        {name: "20",    value: "pt-20",    info: "padding-top: 5rem; /* 80px */"},
        {name: "16",    value: "pt-16",    info: "padding-top: 4rem; /* 64px */"},
        {name: "14",    value: "pt-14",    info: "padding-top: 3.5rem; /* 56px */"},
        {name: "12",    value: "pt-12",    info: "padding-top: 3rem; /* 48px */"},
        {name: "11",    value: "pt-11",    info: "padding-top: 2.75rem; /* 44px */"},
        {name: "10",    value: "pt-10",    info: "padding-top: 2.5rem; /* 40px */"},
        {name: "9",     value: "pt-9",     info: "padding-top: 2.25rem; /* 36px */"},
        {name: "8",     value: "pt-8",     info: "padding-top: 2rem; /* 32px */"},
        {name: "7",     value: "pt-7",     info: "padding-top: 1.75rem; /* 28px */"},
        {name: "6",     value: "pt-6",     info: "padding-top: 1.5rem; /* 24px */"},
        {name: "5",     value: "pt-5",     info: "padding-top: 1.25rem; /* 20px */"},
        {name: "4",     value: "pt-4",     info: "padding-top: 1rem; /* 16px */"},
        {name: "3.5",   value: "pt-3.5",   info: "padding-top: 0.875rem; /* 14px */"},
        {name: "3",     value: "pt-3",     info: "padding-top: 0.75rem; /* 12px */"},
        {name: "2.5",   value: "pt-2.5",   info: "padding-top: 0.625rem; /* 10px */"},
        {name: "2",     value: "pt-2",     info: "padding-top: 0.5rem; /* 8px */"},
        {name: "1.5",   value: "pt-1.5",   info: "padding-top: 0.375rem; /* 6px */"},
        {name: "1",     value: "pt-1",     info: "padding-top: 0.25rem; /* 4px */"},
        {name: "0.5",   value: "pt-0.5",   info: "padding-top: 0.125rem; /* 2px */"},
        {name: "px",    value: "pt-px",    info: "padding-top: 1px;"},

        {name: "-",     value: "",          info: "Default - No value"},
        {name: "0",     value: "pt-0",     info: "padding-top: 0px;"},

    ];

    /**
     * Tailwind Padding Left classes
     * @type Array<SelectOptions>
     */
    export let paddingBottomClassOptions = [
        {name: "96",    value: "pb-96",    info: "padding-bottom: 24rem; /* 384px */"},
        {name: "80",    value: "pb-80",    info: "padding-bottom: 20rem; /* 320px */"},
        {name: "72",    value: "pb-72",    info: "padding-bottom: 18rem; /* 288px */"},
        {name: "64",    value: "pb-64",    info: "padding-bottom: 16rem; /* 256px */"},
        {name: "60",    value: "pb-60",    info: "padding-bottom: 15rem; /* 240px */"},
        {name: "56",    value: "pb-56",    info: "padding-bottom: 14rem; /* 224px */"},
        {name: "52",    value: "pb-52",    info: "padding-bottom: 13rem; /* 208px */"},
        {name: "48",    value: "pb-48",    info: "padding-bottom: 12rem; /* 192px */"},
        {name: "44",    value: "pb-44",    info: "padding-bottom: 11rem; /* 176px */"},
        {name: "40",    value: "pb-40",    info: "padding-bottom: 10rem; /* 160px */"},
        {name: "36",    value: "pb-36",    info: "padding-bottom: 9rem; /* 144px */"},
        {name: "32",    value: "pb-32",    info: "padding-bottom: 8rem; /* 128px */"},
        {name: "28",    value: "pb-28",    info: "padding-bottom: 7rem; /* 112px */"},
        {name: "24",    value: "pb-24",    info: "padding-bottom: 6rem; /* 96px */"},
        {name: "20",    value: "pb-20",    info: "padding-bottom: 5rem; /* 80px */"},
        {name: "16",    value: "pb-16",    info: "padding-bottom: 4rem; /* 64px */"},
        {name: "14",    value: "pb-14",    info: "padding-bottom: 3.5rem; /* 56px */"},
        {name: "12",    value: "pb-12",    info: "padding-bottom: 3rem; /* 48px */"},
        {name: "11",    value: "pb-11",    info: "padding-bottom: 2.75rem; /* 44px */"},
        {name: "10",    value: "pb-10",    info: "padding-bottom: 2.5rem; /* 40px */"},
        {name: "9",     value: "pb-9",     info: "padding-bottom: 2.25rem; /* 36px */"},
        {name: "8",     value: "pb-8",     info: "padding-bottom: 2rem; /* 32px */"},
        {name: "7",     value: "pb-7",     info: "padding-bottom: 1.75rem; /* 28px */"},
        {name: "6",     value: "pb-6",     info: "padding-bottom: 1.5rem; /* 24px */"},
        {name: "5",     value: "pb-5",     info: "padding-bottom: 1.25rem; /* 20px */"},
        {name: "4",     value: "pb-4",     info: "padding-bottom: 1rem; /* 16px */"},
        {name: "3.5",   value: "pb-3.5",   info: "padding-bottom: 0.875rem; /* 14px */"},
        {name: "3",     value: "pb-3",     info: "padding-bottom: 0.75rem; /* 12px */"},
        {name: "2.5",   value: "pb-2.5",   info: "padding-bottom: 0.625rem; /* 10px */"},
        {name: "2",     value: "pb-2",     info: "padding-bottom: 0.5rem; /* 8px */"},
        {name: "1.5",   value: "pb-1.5",   info: "padding-bottom: 0.375rem; /* 6px */"},
        {name: "1",     value: "pb-1",     info: "padding-bottom: 0.25rem; /* 4px */"},
        {name: "0.5",   value: "pb-0.5",   info: "padding-bottom: 0.125rem; /* 2px */"},
        {name: "px",    value: "pb-px",    info: "padding-bottom: 1px;"},

        {name: "-",     value: "",          info: "Default - No value"},
        {name: "0",     value: "pb-0",     info: "padding-bottom: 0px;"},

    ];




    /**
     * Tailwind margin Left classes
     * @type Array<SelectOptions>
     */
    export let marginLeftClassOptions = [

        {name: "96",    value: "ml-96",    info: "margin-left: 24rem; /* 384px */"},
        {name: "80",    value: "ml-80",    info: "margin-left: 20rem; /* 320px */"},
        {name: "72",    value: "ml-72",    info: "margin-left: 18rem; /* 288px */"},
        {name: "64",    value: "ml-64",    info: "margin-left: 16rem; /* 256px */"},
        {name: "60",    value: "ml-60",    info: "margin-left: 15rem; /* 240px */"},
        {name: "56",    value: "ml-56",    info: "margin-left: 14rem; /* 224px */"},
        {name: "52",    value: "ml-52",    info: "margin-left: 13rem; /* 208px */"},
        {name: "48",    value: "ml-48",    info: "margin-left: 12rem; /* 192px */"},
        {name: "44",    value: "ml-44",    info: "margin-left: 11rem; /* 176px */"},
        {name: "40",    value: "ml-40",    info: "margin-left: 10rem; /* 160px */"},
        {name: "36",    value: "ml-36",    info: "margin-left: 9rem; /* 144px */"},
        {name: "32",    value: "ml-32",    info: "margin-left: 8rem; /* 128px */"},
        {name: "28",    value: "ml-28",    info: "margin-left: 7rem; /* 112px */"},
        {name: "24",    value: "ml-24",    info: "margin-left: 6rem; /* 96px */"},
        {name: "20",    value: "ml-20",    info: "margin-left: 5rem; /* 80px */"},
        {name: "16",    value: "ml-16",    info: "margin-left: 4rem; /* 64px */"},
        {name: "14",    value: "ml-14",    info: "margin-left: 3.5rem; /* 56px */"},
        {name: "12",    value: "ml-12",    info: "margin-left: 3rem; /* 48px */"},
        {name: "11",    value: "ml-11",    info: "margin-left: 2.75rem; /* 44px */"},
        {name: "10",    value: "ml-10",    info: "margin-left: 2.5rem; /* 40px */"},
        {name: "9",     value: "ml-9",     info: "margin-left: 2.25rem; /* 36px */"},
        {name: "8",     value: "ml-8",     info: "margin-left: 2rem; /* 32px */"},
        {name: "7",     value: "ml-7",     info: "margin-left: 1.75rem; /* 28px */"},
        {name: "6",     value: "ml-6",     info: "margin-left: 1.5rem; /* 24px */"},
        {name: "5",     value: "ml-5",     info: "margin-left: 1.25rem; /* 20px */"},
        {name: "4",     value: "ml-4",     info: "margin-left: 1rem; /* 16px */"},
        {name: "3.5",   value: "ml-3.5",   info: "margin-left: 0.875rem; /* 14px */"},
        {name: "3",     value: "ml-3",     info: "margin-left: 0.75rem; /* 12px */"},
        {name: "2.5",   value: "ml-2.5",   info: "margin-left: 0.625rem; /* 10px */"},
        {name: "2",     value: "ml-2",     info: "margin-left: 0.5rem; /* 8px */"},
        {name: "1.5",   value: "ml-1.5",   info: "margin-left: 0.375rem; /* 6px */"},
        {name: "1",     value: "ml-1",     info: "margin-left: 0.25rem; /* 4px */"},
        {name: "0.5",   value: "ml-0.5",   info: "margin-left: 0.125rem; /* 2px */"},
        {name: "px",    value: "ml-px",    info: "margin-left: 1px;"},

        {name: "-",     value: "",         info: "Default - No value"},
        {name: "0",     value: "ml-0",     info: "margin-left: 0px;"},
    ];


    /**
    * Tailwind margin Left classes
    * @type Array<SelectOptions>
    */
    export let marginRightClassOptions = [
        {name: "96",    value: "mr-96",    info: "margin-right: 24rem; /* 384px */"},
        {name: "80",    value: "mr-80",    info: "margin-right: 20rem; /* 320px */"},
        {name: "72",    value: "mr-72",    info: "margin-right: 18rem; /* 288px */"},
        {name: "64",    value: "mr-64",    info: "margin-right: 16rem; /* 256px */"},
        {name: "60",    value: "mr-60",    info: "margin-right: 15rem; /* 240px */"},
        {name: "56",    value: "mr-56",    info: "margin-right: 14rem; /* 224px */"},
        {name: "52",    value: "mr-52",    info: "margin-right: 13rem; /* 208px */"},
        {name: "48",    value: "mr-48",    info: "margin-right: 12rem; /* 192px */"},
        {name: "44",    value: "mr-44",    info: "margin-right: 11rem; /* 176px */"},
        {name: "40",    value: "mr-40",    info: "margin-right: 10rem; /* 160px */"},
        {name: "36",    value: "mr-36",    info: "margin-right: 9rem; /* 144px */"},
        {name: "32",    value: "mr-32",    info: "margin-right: 8rem; /* 128px */"},
        {name: "28",    value: "mr-28",    info: "margin-right: 7rem; /* 112px */"},
        {name: "24",    value: "mr-24",    info: "margin-right: 6rem; /* 96px */"},
        {name: "20",    value: "mr-20",    info: "margin-right: 5rem; /* 80px */"},
        {name: "16",    value: "mr-16",    info: "margin-right: 4rem; /* 64px */"},
        {name: "14",    value: "mr-14",    info: "margin-right: 3.5rem; /* 56px */"},
        {name: "12",    value: "mr-12",    info: "margin-right: 3rem; /* 48px */"},
        {name: "11",    value: "mr-11",    info: "margin-right: 2.75rem; /* 44px */"},
        {name: "10",    value: "mr-10",    info: "margin-right: 2.5rem; /* 40px */"},
        {name: "9",     value: "mr-9",     info: "margin-right: 2.25rem; /* 36px */"},
        {name: "8",     value: "mr-8",     info: "margin-right: 2rem; /* 32px */"},
        {name: "7",     value: "mr-7",     info: "margin-right: 1.75rem; /* 28px */"},
        {name: "6",     value: "mr-6",     info: "margin-right: 1.5rem; /* 24px */"},
        {name: "5",     value: "mr-5",     info: "margin-right: 1.25rem; /* 20px */"},
        {name: "4",     value: "mr-4",     info: "margin-right: 1rem; /* 16px */"},
        {name: "3.5",   value: "mr-3.5",   info: "margin-right: 0.875rem; /* 14px */"},
        {name: "3",     value: "mr-3",     info: "margin-right: 0.75rem; /* 12px */"},
        {name: "2.5",   value: "mr-2.5",   info: "margin-right: 0.625rem; /* 10px */"},
        {name: "2",     value: "mr-2",     info: "margin-right: 0.5rem; /* 8px */"},
        {name: "1.5",   value: "mr-1.5",   info: "margin-right: 0.375rem; /* 6px */"},
        {name: "1",     value: "mr-1",     info: "margin-right: 0.25rem; /* 4px */"},
        {name: "0.5",   value: "mr-0.5",   info: "margin-right: 0.125rem; /* 2px */"},
        {name: "px",    value: "mr-px",    info: "margin-right: 1px;"},

        {name: "-",     value: "",          info: "Default - No value"},
        {name: "0",     value: "mr-0",     info: "margin-right: 0px;"},

    ];

    /**
    * Tailwind margin Left classes
    * @type Array<SelectOptions>
    */
    export let marginTopClassOptions = [
        {name: "96",    value: "mt-96",    info: "margin-top: 24rem; /* 384px */"},
        {name: "80",    value: "mt-80",    info: "margin-top: 20rem; /* 320px */"},
        {name: "72",    value: "mt-72",    info: "margin-top: 18rem; /* 288px */"},
        {name: "64",    value: "mt-64",    info: "margin-top: 16rem; /* 256px */"},
        {name: "60",    value: "mt-60",    info: "margin-top: 15rem; /* 240px */"},
        {name: "56",    value: "mt-56",    info: "margin-top: 14rem; /* 224px */"},
        {name: "52",    value: "mt-52",    info: "margin-top: 13rem; /* 208px */"},
        {name: "48",    value: "mt-48",    info: "margin-top: 12rem; /* 192px */"},
        {name: "44",    value: "mt-44",    info: "margin-top: 11rem; /* 176px */"},
        {name: "40",    value: "mt-40",    info: "margin-top: 10rem; /* 160px */"},
        {name: "36",    value: "mt-36",    info: "margin-top: 9rem; /* 144px */"},
        {name: "32",    value: "mt-32",    info: "margin-top: 8rem; /* 128px */"},
        {name: "28",    value: "mt-28",    info: "margin-top: 7rem; /* 112px */"},
        {name: "24",    value: "mt-24",    info: "margin-top: 6rem; /* 96px */"},
        {name: "20",    value: "mt-20",    info: "margin-top: 5rem; /* 80px */"},
        {name: "16",    value: "mt-16",    info: "margin-top: 4rem; /* 64px */"},
        {name: "14",    value: "mt-14",    info: "margin-top: 3.5rem; /* 56px */"},
        {name: "12",    value: "mt-12",    info: "margin-top: 3rem; /* 48px */"},
        {name: "11",    value: "mt-11",    info: "margin-top: 2.75rem; /* 44px */"},
        {name: "10",    value: "mt-10",    info: "margin-top: 2.5rem; /* 40px */"},
        {name: "9",     value: "mt-9",     info: "margin-top: 2.25rem; /* 36px */"},
        {name: "8",     value: "mt-8",     info: "margin-top: 2rem; /* 32px */"},
        {name: "7",     value: "mt-7",     info: "margin-top: 1.75rem; /* 28px */"},
        {name: "6",     value: "mt-6",     info: "margin-top: 1.5rem; /* 24px */"},
        {name: "5",     value: "mt-5",     info: "margin-top: 1.25rem; /* 20px */"},
        {name: "4",     value: "mt-4",     info: "margin-top: 1rem; /* 16px */"},
        {name: "3.5",   value: "mt-3.5",   info: "margin-top: 0.875rem; /* 14px */"},
        {name: "3",     value: "mt-3",     info: "margin-top: 0.75rem; /* 12px */"},
        {name: "2.5",   value: "mt-2.5",   info: "margin-top: 0.625rem; /* 10px */"},
        {name: "2",     value: "mt-2",     info: "margin-top: 0.5rem; /* 8px */"},
        {name: "1.5",   value: "mt-1.5",   info: "margin-top: 0.375rem; /* 6px */"},
        {name: "1",     value: "mt-1",     info: "margin-top: 0.25rem; /* 4px */"},
        {name: "0.5",   value: "mt-0.5",   info: "margin-top: 0.125rem; /* 2px */"},
        {name: "px",    value: "mt-px",    info: "margin-top: 1px;"},

        {name: "-",     value: "",          info: "Default - No value"},
        {name: "0",     value: "mt-0",     info: "margin-top: 0px;"},

    ];

    /**
    * Tailwind margin Left classes
    * @type Array<SelectOptions>
    */
    export let marginBottomClassOptions = [
        {name: "96",    value: "mb-96",    info: "margin-bottom: 24rem; /* 384px */"},
        {name: "80",    value: "mb-80",    info: "margin-bottom: 20rem; /* 320px */"},
        {name: "72",    value: "mb-72",    info: "margin-bottom: 18rem; /* 288px */"},
        {name: "64",    value: "mb-64",    info: "margin-bottom: 16rem; /* 256px */"},
        {name: "60",    value: "mb-60",    info: "margin-bottom: 15rem; /* 240px */"},
        {name: "56",    value: "mb-56",    info: "margin-bottom: 14rem; /* 224px */"},
        {name: "52",    value: "mb-52",    info: "margin-bottom: 13rem; /* 208px */"},
        {name: "48",    value: "mb-48",    info: "margin-bottom: 12rem; /* 192px */"},
        {name: "44",    value: "mb-44",    info: "margin-bottom: 11rem; /* 176px */"},
        {name: "40",    value: "mb-40",    info: "margin-bottom: 10rem; /* 160px */"},
        {name: "36",    value: "mb-36",    info: "margin-bottom: 9rem; /* 144px */"},
        {name: "32",    value: "mb-32",    info: "margin-bottom: 8rem; /* 128px */"},
        {name: "28",    value: "mb-28",    info: "margin-bottom: 7rem; /* 112px */"},
        {name: "24",    value: "mb-24",    info: "margin-bottom: 6rem; /* 96px */"},
        {name: "20",    value: "mb-20",    info: "margin-bottom: 5rem; /* 80px */"},
        {name: "16",    value: "mb-16",    info: "margin-bottom: 4rem; /* 64px */"},
        {name: "14",    value: "mb-14",    info: "margin-bottom: 3.5rem; /* 56px */"},
        {name: "12",    value: "mb-12",    info: "margin-bottom: 3rem; /* 48px */"},
        {name: "11",    value: "mb-11",    info: "margin-bottom: 2.75rem; /* 44px */"},
        {name: "10",    value: "mb-10",    info: "margin-bottom: 2.5rem; /* 40px */"},
        {name: "9",     value: "mb-9",     info: "margin-bottom: 2.25rem; /* 36px */"},
        {name: "8",     value: "mb-8",     info: "margin-bottom: 2rem; /* 32px */"},
        {name: "7",     value: "mb-7",     info: "margin-bottom: 1.75rem; /* 28px */"},
        {name: "6",     value: "mb-6",     info: "margin-bottom: 1.5rem; /* 24px */"},
        {name: "5",     value: "mb-5",     info: "margin-bottom: 1.25rem; /* 20px */"},
        {name: "4",     value: "mb-4",     info: "margin-bottom: 1rem; /* 16px */"},
        {name: "3.5",   value: "mb-3.5",   info: "margin-bottom: 0.875rem; /* 14px */"},
        {name: "3",     value: "mb-3",     info: "margin-bottom: 0.75rem; /* 12px */"},
        {name: "2.5",   value: "mb-2.5",   info: "margin-bottom: 0.625rem; /* 10px */"},
        {name: "2",     value: "mb-2",     info: "margin-bottom: 0.5rem; /* 8px */"},
        {name: "1.5",   value: "mb-1.5",   info: "margin-bottom: 0.375rem; /* 6px */"},
        {name: "1",     value: "mb-1",     info: "margin-bottom: 0.25rem; /* 4px */"},
        {name: "0.5",   value: "mb-0.5",   info: "margin-bottom: 0.125rem; /* 2px */"},
        {name: "px",    value: "mb-px",    info: "margin-bottom: 1px;"},

        {name: "-",     value: "",          info: "Default - No value"},
        {name: "0",     value: "mb-0",     info: "margin-bottom: 0px;"},

    ];



    /**
    * Tailwind Width classes
    * @type Array<SelectOptions>
    */
    export let widthClassOptions = [

        {name: "fit",     value: "w-fit",     info: "width: fit-content;"},
        {name: "max",     value: "w-max",     info: "width: max-content;"},
        {name: "min",     value: "w-min",     info: "width: min-content;"},
        {name: "screen",  value: "w-screen",  info: "width: 100vw;"},
        {name: "full",    value: "w-full",    info: "width: 100%;"},
        {name: "11/12",   value: "w-11/12",   info: "width: 91.666667%;"},
        {name: "10/12",   value: "w-10/12",   info: "width: 83.333333%;"},
        {name: "9/12",    value: "w-9/12",    info: "width: 75%;"},
        {name: "8/12",    value: "w-8/12",    info: "width: 66.666667%;"},
        {name: "7/12",    value: "w-7/12",    info: "width: 58.333333%;"},
        {name: "6/12",    value: "w-6/12",    info: "width: 50%;"},
        {name: "5/12",    value: "w-5/12",    info: "width: 41.666667%;"},
        {name: "4/12",    value: "w-4/12",    info: "width: 33.333333%;"},
        {name: "3/12",    value: "w-3/12",    info: "width: 25%;"},
        {name: "2/12",    value: "w-2/12",    info: "width: 16.666667%;"},
        {name: "1/12",    value: "w-1/12",    info: "width: 8.333333%;"},
        {name: "5/6",     value: "w-5/6",     info: "width: 83.333333%;"},
        {name: "4/6",     value: "w-4/6",     info: "width: 66.666667%;"},
        {name: "3/6",     value: "w-3/6",     info: "width: 50%;"},
        {name: "2/6",     value: "w-2/6",     info: "width: 33.333333%;"},
        {name: "1/6",     value: "w-1/6",     info: "width: 16.666667%;"},
        {name: "4/5",     value: "w-4/5",     info: "width: 80%;"},
        {name: "3/5",     value: "w-3/5",     info: "width: 60%;"},
        {name: "2/5",     value: "w-2/5",     info: "width: 40%;"},
        {name: "1/5",     value: "w-1/5",     info: "width: 20%;"},
        {name: "3/4",     value: "w-3/4",     info: "width: 75%;"},
        {name: "2/4",     value: "w-2/4",     info: "width: 50%;"},
        {name: "1/4",     value: "w-1/4",     info: "width: 25%;"},
        {name: "2/3",     value: "w-2/3",     info: "width: 66.666667%;"},
        {name: "1/3",     value: "w-1/3",     info: "width: 33.333333%;"},
        {name: "1/2",     value: "w-1/2",     info: "width: 50%;"},
        {name: "auto",    value: "w-auto",    info: "width: auto;"},

        {name: "96",    value: "w-96",    info: "width: 24rem; /* 384px */"},
        {name: "80",    value: "w-80",    info: "width: 20rem; /* 320px */"},
        {name: "72",    value: "w-72",    info: "width: 18rem; /* 288px */"},
        {name: "64",    value: "w-64",    info: "width: 16rem; /* 256px */"},
        {name: "60",    value: "w-60",    info: "width: 15rem; /* 240px */"},
        {name: "56",    value: "w-56",    info: "width: 14rem; /* 224px */"},
        {name: "52",    value: "w-52",    info: "width: 13rem; /* 208px */"},
        {name: "48",    value: "w-48",    info: "width: 12rem; /* 192px */"},
        {name: "44",    value: "w-44",    info: "width: 11rem; /* 176px */"},
        {name: "40",    value: "w-40",    info: "width: 10rem; /* 160px */"},
        {name: "36",    value: "w-36",    info: "width: 9rem; /* 144px */"},
        {name: "32",    value: "w-32",    info: "width: 8rem; /* 128px */"},
        {name: "28",    value: "w-28",    info: "width: 7rem; /* 112px */"},
        {name: "24",    value: "w-24",    info: "width: 6rem; /* 96px */"},
        {name: "20",    value: "w-20",    info: "width: 5rem; /* 80px */"},
        {name: "16",    value: "w-16",    info: "width: 4rem; /* 64px */"},
        {name: "14",    value: "w-14",    info: "width: 3.5rem; /* 56px */"},
        {name: "12",    value: "w-12",    info: "width: 3rem; /* 48px */"},
        {name: "11",    value: "w-11",    info: "width: 2.75rem; /* 44px */"},
        {name: "10",    value: "w-10",    info: "width: 2.5rem; /* 40px */"},
        {name: "9",     value: "w-9",     info: "width: 2.25rem; /* 36px */"},
        {name: "8",     value: "w-8",     info: "width: 2rem; /* 32px */"},
        {name: "7",     value: "w-7",     info: "width: 1.75rem; /* 28px */"},
        {name: "6",     value: "w-6",     info: "width: 1.5rem; /* 24px */"},
        {name: "5",     value: "w-5",     info: "width: 1.25rem; /* 20px */"},
        {name: "4",     value: "w-4",     info: "width: 1rem; /* 16px */"},
        {name: "3.5",   value: "w-3.5",   info: "width: 0.875rem; /* 14px */"},
        {name: "3",     value: "w-3",     info: "width: 0.75rem; /* 12px */"},
        {name: "2.5",   value: "w-2.5",   info: "width: 0.625rem; /* 10px */"},
        {name: "2",     value: "w-2",     info: "width: 0.5rem; /* 8px */"},
        {name: "1.5",   value: "w-1.5",   info: "width: 0.375rem; /* 6px */"},
        {name: "1",     value: "w-1",     info: "width: 0.25rem; /* 4px */"},
        {name: "0.5",   value: "w-0.5",   info: "width: 0.125rem; /* 2px */"},
        {name: "px",    value: "w-px",    info: "width: 1px;"},
        {name: "0",     value: "w-0",     info: "width: 0px;"},
        {name: "-",     value: "",        info: "Default - No value"},

    ];


    /**
    * Tailwind Height classes
    * @type Array<SelectOptions>
    */
    export let heightClassOptions = [

        {name: "fit",     value: "h-fit",     info: "height: fit-content;"},
        {name: "max",     value: "h-max",     info: "height: max-content;"},
        {name: "min",     value: "h-min",     info: "height: min-content;"},
        {name: "screen",  value: "h-screen",  info: "height: 100vw;"},
        {name: "full",    value: "h-full",    info: "height: 100%;"},
        {name: "11/12",   value: "h-11/12",   info: "height: 91.666667%;"},
        {name: "10/12",   value: "h-10/12",   info: "height: 83.333333%;"},
        {name: "9/12",    value: "h-9/12",    info: "height: 75%;"},
        {name: "8/12",    value: "h-8/12",    info: "height: 66.666667%;"},
        {name: "7/12",    value: "h-7/12",    info: "height: 58.333333%;"},
        {name: "6/12",    value: "h-6/12",    info: "height: 50%;"},
        {name: "5/12",    value: "h-5/12",    info: "height: 41.666667%;"},
        {name: "4/12",    value: "h-4/12",    info: "height: 33.333333%;"},
        {name: "3/12",    value: "h-3/12",    info: "height: 25%;"},
        {name: "2/12",    value: "h-2/12",    info: "height: 16.666667%;"},
        {name: "1/12",    value: "h-1/12",    info: "height: 8.333333%;"},
        {name: "5/6",     value: "h-5/6",     info: "height: 83.333333%;"},
        {name: "4/6",     value: "h-4/6",     info: "height: 66.666667%;"},
        {name: "3/6",     value: "h-3/6",     info: "height: 50%;"},
        {name: "2/6",     value: "h-2/6",     info: "height: 33.333333%;"},
        {name: "1/6",     value: "h-1/6",     info: "height: 16.666667%;"},
        {name: "4/5",     value: "h-4/5",     info: "height: 80%;"},
        {name: "3/5",     value: "h-3/5",     info: "height: 60%;"},
        {name: "2/5",     value: "h-2/5",     info: "height: 40%;"},
        {name: "1/5",     value: "h-1/5",     info: "height: 20%;"},
        {name: "3/4",     value: "h-3/4",     info: "height: 75%;"},
        {name: "2/4",     value: "h-2/4",     info: "height: 50%;"},
        {name: "1/4",     value: "h-1/4",     info: "height: 25%;"},
        {name: "2/3",     value: "h-2/3",     info: "height: 66.666667%;"},
        {name: "1/3",     value: "h-1/3",     info: "height: 33.333333%;"},
        {name: "1/2",     value: "h-1/2",     info: "height: 50%;"},
        {name: "auto",    value: "h-auto",    info: "height: auto;"},

        {name: "96",    value: "h-96",    info: "height: 24rem; /* 384px */"},
        {name: "80",    value: "h-80",    info: "height: 20rem; /* 320px */"},
        {name: "72",    value: "h-72",    info: "height: 18rem; /* 288px */"},
        {name: "64",    value: "h-64",    info: "height: 16rem; /* 256px */"},
        {name: "60",    value: "h-60",    info: "height: 15rem; /* 240px */"},
        {name: "56",    value: "h-56",    info: "height: 14rem; /* 224px */"},
        {name: "52",    value: "h-52",    info: "height: 13rem; /* 208px */"},
        {name: "48",    value: "h-48",    info: "height: 12rem; /* 192px */"},
        {name: "44",    value: "h-44",    info: "height: 11rem; /* 176px */"},
        {name: "40",    value: "h-40",    info: "height: 10rem; /* 160px */"},
        {name: "36",    value: "h-36",    info: "height: 9rem; /* 144px */"},
        {name: "32",    value: "h-32",    info: "height: 8rem; /* 128px */"},
        {name: "28",    value: "h-28",    info: "height: 7rem; /* 112px */"},
        {name: "24",    value: "h-24",    info: "height: 6rem; /* 96px */"},
        {name: "20",    value: "h-20",    info: "height: 5rem; /* 80px */"},
        {name: "16",    value: "h-16",    info: "height: 4rem; /* 64px */"},
        {name: "14",    value: "h-14",    info: "height: 3.5rem; /* 56px */"},
        {name: "12",    value: "h-12",    info: "height: 3rem; /* 48px */"},
        {name: "11",    value: "h-11",    info: "height: 2.75rem; /* 44px */"},
        {name: "10",    value: "h-10",    info: "height: 2.5rem; /* 40px */"},
        {name: "9",     value: "h-9",     info: "height: 2.25rem; /* 36px */"},
        {name: "8",     value: "h-8",     info: "height: 2rem; /* 32px */"},
        {name: "7",     value: "h-7",     info: "height: 1.75rem; /* 28px */"},
        {name: "6",     value: "h-6",     info: "height: 1.5rem; /* 24px */"},
        {name: "5",     value: "h-5",     info: "height: 1.25rem; /* 20px */"},
        {name: "4",     value: "h-4",     info: "height: 1rem; /* 16px */"},
        {name: "3.5",   value: "h-3.5",   info: "height: 0.875rem; /* 14px */"},
        {name: "3",     value: "h-3",     info: "height: 0.75rem; /* 12px */"},
        {name: "2.5",   value: "h-2.5",   info: "height: 0.625rem; /* 10px */"},
        {name: "2",     value: "h-2",     info: "height: 0.5rem; /* 8px */"},
        {name: "1.5",   value: "h-1.5",   info: "height: 0.375rem; /* 6px */"},
        {name: "1",     value: "h-1",     info: "height: 0.25rem; /* 4px */"},
        {name: "0.5",   value: "h-0.5",   info: "height: 0.125rem; /* 2px */"},
        {name: "px",    value: "h-px",    info: "height: 1px;"},
        {name: "0",     value: "h-0",     info: "height: 0px;"},
        {name: "-",     value: "",        info: "Default - No value"},

    ];


    /**
    * Tailwind Minimum Height classes
    * @type Array<SelectOptions>
    */
    export let minHeightClassOptions = [
        {name: "-",       value: "",              info: "Default - No value"},
        {name: "0",       value: "min-h-0",       info: "min-height: 0px;"},
        {name: "full",    value: "min-h-full",    info: "min-height: 100%;"},
        {name: "screen",  value: "min-h-screen",  info: "min-height: 100vh;"},
        {name: "min",     value: "min-h-min",     info: "min-height: min-content;"},
        {name: "max",     value: "min-h-max",     info: "min-height: max-content;"},
        {name: "fit",     value: "min-h-fit",     info: "min-height: fit-content;"},
    ];


    /**
    * Tailwind Maximum Height classes
    * @type Array<SelectOptions>
    */
    export let maxHeightClassOptions = [

        {name: "none",    value: "max-h-none",    info: "max-height: none;"},
        {name: "full",    value: "max-h-full",    info: "max-height: 100%;"},
        {name: "screen",  value: "max-h-screen",  info: "max-height: 100vh;"},
        {name: "min",     value: "max-h-min",     info: "max-height: min-content;"},
        {name: "max",     value: "max-h-max",     info: "max-height: max-content;"},
        {name: "fit",     value: "max-h-fit",     info: "max-height: fit-content;"},

        {name: "96",    value: "max-h-96",    info: "max-height: 24rem; /* 384px */"},
        {name: "80",    value: "max-h-80",    info: "max-height: 20rem; /* 320px */"},
        {name: "72",    value: "max-h-72",    info: "max-height: 18rem; /* 288px */"},
        {name: "64",    value: "max-h-64",    info: "max-height: 16rem; /* 256px */"},
        {name: "60",    value: "max-h-60",    info: "max-height: 15rem; /* 240px */"},
        {name: "56",    value: "max-h-56",    info: "max-height: 14rem; /* 224px */"},
        {name: "52",    value: "max-h-52",    info: "max-height: 13rem; /* 208px */"},
        {name: "48",    value: "max-h-48",    info: "max-height: 12rem; /* 192px */"},
        {name: "44",    value: "max-h-44",    info: "max-height: 11rem; /* 176px */"},
        {name: "40",    value: "max-h-40",    info: "max-height: 10rem; /* 160px */"},
        {name: "36",    value: "max-h-36",    info: "max-height: 9rem; /* 144px */"},
        {name: "32",    value: "max-h-32",    info: "max-height: 8rem; /* 128px */"},
        {name: "28",    value: "max-h-28",    info: "max-height: 7rem; /* 112px */"},
        {name: "24",    value: "max-h-24",    info: "max-height: 6rem; /* 96px */"},
        {name: "20",    value: "max-h-20",    info: "max-height: 5rem; /* 80px */"},
        {name: "16",    value: "max-h-16",    info: "max-height: 4rem; /* 64px */"},
        {name: "14",    value: "max-h-14",    info: "max-height: 3.5rem; /* 56px */"},
        {name: "12",    value: "max-h-12",    info: "max-height: 3rem; /* 48px */"},
        {name: "11",    value: "max-h-11",    info: "max-height: 2.75rem; /* 44px */"},
        {name: "10",    value: "max-h-10",    info: "max-height: 2.5rem; /* 40px */"},
        {name: "9",     value: "max-h-9",     info: "max-height: 2.25rem; /* 36px */"},
        {name: "8",     value: "max-h-8",     info: "max-height: 2rem; /* 32px */"},
        {name: "7",     value: "max-h-7",     info: "max-height: 1.75rem; /* 28px */"},
        {name: "6",     value: "max-h-6",     info: "max-height: 1.5rem; /* 24px */"},
        {name: "5",     value: "max-h-5",     info: "max-height: 1.25rem; /* 20px */"},
        {name: "4",     value: "max-h-4",     info: "max-height: 1rem; /* 16px */"},
        {name: "3.5",   value: "max-h-3.5",   info: "max-height: 0.875rem; /* 14px */"},
        {name: "3",     value: "max-h-3",     info: "max-height: 0.75rem; /* 12px */"},
        {name: "2.5",   value: "max-h-2.5",   info: "max-height: 0.625rem; /* 10px */"},
        {name: "2",     value: "max-h-2",     info: "max-height: 0.5rem; /* 8px */"},
        {name: "1.5",   value: "max-h-1.5",   info: "max-height: 0.375rem; /* 6px */"},
        {name: "1",     value: "max-h-1",     info: "max-height: 0.25rem; /* 4px */"},
        {name: "0.5",   value: "max-h-0.5",   info: "max-height: 0.125rem; /* 2px */"},
        {name: "px",    value: "max-h-px",    info: "max-height: 1px;"},
        {name: "0",     value: "max-h-0",     info: "max-height: 0px;"},
        {name: "-",     value: "",        info: "Default - No value"},
    ];

    /**
    * Tailwind Minimum Width classes
    * @type Array<SelectOptions>
    */
    export let minWidthClassOptions = [
        {name: "-",       value: "",              info: "Default - No value"},
        {name: "0	",    value: "min-w-0",       info: "min-width: 0px;"},
        {name: "full",    value: "min-w-full",    info: "min-width: 100%;"},
        {name: "min",     value: "min-w-min",     info: "min-width: min-content;"},
        {name: "max",     value: "min-w-max",     info: "min-width: max-content;"},
        {name: "fit",     value: "min-w-fit",     info: "min-width: fit-content;"},
    ];

    /**
    * Tailwind Maximum Width classes
    * @type Array<SelectOptions>
    */
    export let maxWidthClassOptions = [
        {name: "-",                 value: "",                  info: "Default - No value"},
        {name: "0",           value: "max-w-0",           info: "max-width: 0rem; /* 0px */"},
        {name: "none",        value: "max-w-none",        info: "max-width: none;"},
        {name: "xs",          value: "max-w-xs",          info: "max-width: 20rem; /* 320px */"},
        {name: "sm",          value: "max-w-sm",          info: "max-width: 24rem; /* 384px */"},
        {name: "md",          value: "max-w-md",          info: "max-width: 28rem; /* 448px */"},
        {name: "lg",          value: "max-w-lg",          info: "max-width: 32rem; /* 512px */"},
        {name: "xl",          value: "max-w-xl",          info: "max-width: 36rem; /* 576px */"},
        {name: "2xl",         value: "max-w-2xl",         info: "max-width: 42rem; /* 672px */"},
        {name: "3xl",         value: "max-w-3xl",         info: "max-width: 48rem; /* 768px */"},
        {name: "4xl",         value: "max-w-4xl",         info: "max-width: 56rem; /* 896px */"},
        {name: "5xl",         value: "max-w-5xl",         info: "max-width: 64rem; /* 1024px */"},
        {name: "6xl",         value: "max-w-6xl",         info: "max-width: 72rem; /* 1152px */"},
        {name: "7xl",         value: "max-w-7xl",         info: "max-width: 80rem; /* 1280px */"},
        {name: "full",        value: "max-w-full",        info: "max-width: 100%;"},
        {name: "min",         value: "max-w-min",         info: "max-width: min-content;"},
        {name: "max",         value: "max-w-max",         info: "max-width: max-content;"},
        {name: "fit",         value: "max-w-fit",         info: "max-width: fit-content;"},
        {name: "prose",       value: "max-w-prose",       info: "max-width: 65ch;"},
        {name: "screen-sm",   value: "max-w-screen-sm",   info: "max-width: 640px;"},
        {name: "screen-md",   value: "max-w-screen-md",   info: "max-width: 768px;"},
        {name: "screen-lg",   value: "max-w-screen-lg",   info: "max-width: 1024px;"},
        {name: "screen-xl",   value: "max-w-screen-xl",   info: "max-width: 1280px;"},
        {name: "screen-2xl",  value: "max-w-screen-2xl",  info: "max-width: 1536px;"},
    ];




    // {name: "",      value: "",      info: ""},
    // {name: "",      value: "",      info: ""},
    // {name: "",      value: "",      info: ""},
    // {name: "",      value: "",      info: ""},
    // {name: "",      value: "",      info: ""},
    // {name: "",      value: "",      info: ""},
    // {name: "",      value: "",      info: ""},
    // {name: "",      value: "",      info: ""},
    // {name: "",      value: "",      info: ""},
    // {name: "",      value: "",      info: ""},
    // {name: "",      value: "",      info: ""},
    // {name: "",      value: "",      info: ""},








</script>

