<script context="module">

    /**
     * @typedef {Object} SelectOptions
     * @property {string} value
     * @property {string} name
     * @property {string} info
    */

    /**
     * CSS Units
     * @type Array<SelectOptions>
     */
    export let cssUnitOptions = [
        {name: "TW",    value: "class", info: "Tailwind Class"},
        {name: "px",    value: "px",    info: "pixels (1px = 1/96th of 1in) "},
        {name: "em",    value: "em",    info: "Relative to the font-size of the element (2em means 2 times the size of the current font)"},
        {name: "rem",   value: "rem",   info: "Relative to font-size of the root element"},
        {name: "vw",    value: "vw",    info: "Relative to 1% of the width of the viewport"},
        {name: "vh",    value: "vh",    info: "Relative to 1% of the height of the viewport"},
        {name: "vmin",  value: "vmin",  info: "Relative to 1% of viewport's* smaller dimension"},
        {name: "vmax",  value: "vmax",  info: "Relative to 1% of viewport's* larger dimension"},
        {name: "%",     value: "%",     info: "Relative to the parent element"},
        {name: "cm",    value: "cm",    info: "centimeters"},
        {name: "mm",    value: "mm",    info: "millimeters"},
        {name: "in",    value: "in",    info: "inches (1in = 96px = 2.54cm) "},
        {name: "pt",    value: "pt",    info: "points (1pt = 1/72 of 1in) "},
        {name: "pc",    value: "pc",    info: "picas (1pc = 12 pt) "},
    ];


    /**
     * Tailwind top- classes
     * @type Array<SelectOptions>
     */
    export let topClassOptions = [

        {name: "full",  value: "top-full",  info: "top: 100%;"},
        {name: "3/4",   value: "top-3/4",   info: "top: 75%;"},
        {name: "2/4",   value: "top-2/4",   info: "top: 50%;"},
        {name: "1/4",   value: "top-1/4",   info: "top: 25%;"},
        {name: "2/3",   value: "top-2/3",   info: "top: 66.666667%;"},
        {name: "1/3",   value: "top-1/3",   info: "top: 33.333333%;"},
        {name: "1/2",   value: "top-1/2",   info: "top: 50%;"},

        {name: "96",    value: "top-96",    info: "top: 24rem; /* 384px */"},
        {name: "80",    value: "top-80",    info: "top: 20rem; /* 320px */"},
        {name: "72",    value: "top-72",    info: "top: 18rem; /* 288px */"},
        {name: "64",    value: "top-64",    info: "top: 16rem; /* 256px */"},
        {name: "60",    value: "top-60",    info: "top: 15rem; /* 240px */"},
        {name: "56",    value: "top-56",    info: "top: 14rem; /* 224px */"},
        {name: "52",    value: "top-52",    info: "top: 13rem; /* 208px */"},
        {name: "48",    value: "top-48",    info: "top: 12rem; /* 192px */"},
        {name: "44",    value: "top-44",    info: "top: 11rem; /* 176px */"},
        {name: "40",    value: "top-40",    info: "top: 10rem; /* 160px */"},
        {name: "36",    value: "top-36",    info: "top: 9rem; /* 144px */"},
        {name: "32",    value: "top-32",    info: "top: 8rem; /* 128px */"},
        {name: "28",    value: "top-28",    info: "top: 7rem; /* 112px */"},
        {name: "24",    value: "top-24",    info: "top: 6rem; /* 96px */"},
        {name: "20",    value: "top-20",    info: "top: 5rem; /* 80px */"},
        {name: "16",    value: "top-16",    info: "top: 4rem; /* 64px */"},
        {name: "14",    value: "top-14",    info: "top: 3.5rem; /* 56px */"},
        {name: "12",    value: "top-12",    info: "top: 3rem; /* 48px */"},
        {name: "11",    value: "top-11",    info: "top: 2.75rem; /* 44px */"},
        {name: "10",    value: "top-10",    info: "top: 2.5rem; /* 40px */"},
        {name: "9",     value: "top-9",     info: "top: 2.25rem; /* 36px */"},
        {name: "8",     value: "top-8",     info: "top: 2rem; /* 32px */"},
        {name: "7",     value: "top-7",     info: "top: 1.75rem; /* 28px */"},
        {name: "6",     value: "top-6",     info: "top: 1.5rem; /* 24px */"},
        {name: "5",     value: "top-5",     info: "top: 1.25rem; /* 20px */"},
        {name: "4",     value: "top-4",     info: "top: 1rem; /* 16px */"},
        {name: "3.5",   value: "top-3.5",   info: "top: 0.875rem; /* 14px */"},
        {name: "3",     value: "top-3",     info: "top: 0.75rem; /* 12px */"},
        {name: "2.5",   value: "top-2.5",   info: "top: 0.625rem; /* 10px */"},
        {name: "2",     value: "top-2",     info: "top: 0.5rem; /* 8px */"},
        {name: "1.5",   value: "top-1.5",   info: "top: 0.375rem; /* 6px */"},
        {name: "1",     value: "top-1",     info: "top: 0.25rem; /* 4px */"},
        {name: "0.5",   value: "top-0.5",   info: "top: 0.125rem; /* 2px */"},
        {name: "px",    value: "top-px",    info: "top: 1px;"},

        {name: "-",     value: "",          info: "Default - No value"},
        {name: "0",     value: "top-0",     info: "top: 0px;"},

        {name: "-px",    value: "-top-px",    info: "top: -1px;"},
        {name: "-0.5",   value: "-top-0.5",   info: "top: -0.125rem; /* -2px */"},
        {name: "-1",     value: "-top-1",     info: "top: -0.25rem; /* -4px */"},
        {name: "-1.5",   value: "-top-1.5",   info: "top: -0.375rem; /* -6px */"},
        {name: "-2",     value: "-top-2",     info: "top: -0.5rem; /* -8px */"},
        {name: "-2.5",   value: "-top-2.5",   info: "top: -0.625rem; /* -10px */"},
        {name: "-3",     value: "-top-3",     info: "top: -0.75rem; /* -12px */"},
        {name: "-3.5",   value: "-top-3.5",   info: "top: -0.875rem; /* -14px */"},
        {name: "-4",     value: "-top-4",     info: "top: -1rem; /* -16px */"},
        {name: "-5",     value: "-top-5",     info: "top: -1.25rem; /* -20px */"},
        {name: "-6",     value: "-top-6",     info: "top: -1.5rem; /* -24px */"},
        {name: "-7",     value: "-top-7",     info: "top: -1.75rem; /* -28px */"},
        {name: "-8",     value: "-top-8",     info: "top: -2rem; /* -32px */"},
        {name: "-9",     value: "-top-9",     info: "top: -2.25rem; /* -36px */"},
        {name: "-10",    value: "-top-10",    info: "top: -2.5rem; /* -40px */"},
        {name: "-11",    value: "-top-11",    info: "top: -2.75rem; /* -44px */"},
        {name: "-12",    value: "-top-12",    info: "top: -3rem; /* -48px */"},
        {name: "-14",    value: "-top-14",    info: "top: -3.5rem; /* -56px */"},
        {name: "-16",    value: "-top-16",    info: "top: -4rem; /* -64px */"},
        {name: "-20",    value: "-top-20",    info: "top: -5rem; /* -80px */"},
        {name: "-24",    value: "-top-24",    info: "top: -6rem; /* -96px */"},
        {name: "-28",    value: "-top-28",    info: "top: -7rem; /* -112px */"},
        {name: "-32",    value: "-top-32",    info: "top: -8rem; /* -128px */"},
        {name: "-36",    value: "-top-36",    info: "top: -9rem; /* -144px */"},
        {name: "-40",    value: "-top-40",    info: "top: -10rem; /* -160px */"},
        {name: "-44",    value: "-top-44",    info: "top: -11rem; /* -176px */"},
        {name: "-48",    value: "-top-48",    info: "top: -12rem; /* -192px */"},
        {name: "-52",    value: "-top-52",    info: "top: -13rem; /* -208px */"},
        {name: "-56",    value: "-top-56",    info: "top: -14rem; /* -224px */"},
        {name: "-60",    value: "-top-60",    info: "top: -15rem; /* -240px */"},
        {name: "-64",    value: "-top-64",    info: "top: -16rem; /* -256px */"},
        {name: "-72",    value: "-top-72",    info: "top: -18rem; /* -288px */"},
        {name: "-80",    value: "-top-80",    info: "top: -20rem; /* -320px */"},
        {name: "-96",    value: "-top-96",    info: "top: -24rem; /* -384px */"},

        {name: "-auto",  value: "-top-auto",  info: "top: -auto;"},
        {name: "-1/2",   value: "-top-1/2",   info: "top: -50%;"},
        {name: "-1/3",   value: "-top-1/3",   info: "top: -33.333333%;"},
        {name: "-2/3",   value: "-top-2/3",   info: "top: -66.666667%;"},
        {name: "-1/4",   value: "-top-1/4",   info: "top: -25%;"},
        {name: "-2/4",   value: "-top-2/4",   info: "top: -50%;"},
        {name: "-3/4",   value: "-top-3/4",   info: "top: -75%;"},
        {name: "-full",  value: "-top-full",  info: "top: -100%;"},

    ];

    /**
     * Tailwind right- classes
     * @type Array<SelectOptions>
     */
    export let rightClassOptions = [
        {name: "full",  value: "right-full",  info: "right: 100%;"},
        {name: "3/4",   value: "right-3/4",   info: "right: 75%;"},
        {name: "2/4",   value: "right-2/4",   info: "right: 50%;"},
        {name: "1/4",   value: "right-1/4",   info: "right: 25%;"},
        {name: "2/3",   value: "right-2/3",   info: "right: 66.666667%;"},
        {name: "1/3",   value: "right-1/3",   info: "right: 33.333333%;"},
        {name: "1/2",   value: "right-1/2",   info: "right: 50%;"},

        {name: "96",    value: "right-96",    info: "right: 24rem; /* 384px */"},
        {name: "80",    value: "right-80",    info: "right: 20rem; /* 320px */"},
        {name: "72",    value: "right-72",    info: "right: 18rem; /* 288px */"},
        {name: "64",    value: "right-64",    info: "right: 16rem; /* 256px */"},
        {name: "60",    value: "right-60",    info: "right: 15rem; /* 240px */"},
        {name: "56",    value: "right-56",    info: "right: 14rem; /* 224px */"},
        {name: "52",    value: "right-52",    info: "right: 13rem; /* 208px */"},
        {name: "48",    value: "right-48",    info: "right: 12rem; /* 192px */"},
        {name: "44",    value: "right-44",    info: "right: 11rem; /* 176px */"},
        {name: "40",    value: "right-40",    info: "right: 10rem; /* 160px */"},
        {name: "36",    value: "right-36",    info: "right: 9rem; /* 144px */"},
        {name: "32",    value: "right-32",    info: "right: 8rem; /* 128px */"},
        {name: "28",    value: "right-28",    info: "right: 7rem; /* 112px */"},
        {name: "24",    value: "right-24",    info: "right: 6rem; /* 96px */"},
        {name: "20",    value: "right-20",    info: "right: 5rem; /* 80px */"},
        {name: "16",    value: "right-16",    info: "right: 4rem; /* 64px */"},
        {name: "14",    value: "right-14",    info: "right: 3.5rem; /* 56px */"},
        {name: "12",    value: "right-12",    info: "right: 3rem; /* 48px */"},
        {name: "11",    value: "right-11",    info: "right: 2.75rem; /* 44px */"},
        {name: "10",    value: "right-10",    info: "right: 2.5rem; /* 40px */"},
        {name: "9",     value: "right-9",     info: "right: 2.25rem; /* 36px */"},
        {name: "8",     value: "right-8",     info: "right: 2rem; /* 32px */"},
        {name: "7",     value: "right-7",     info: "right: 1.75rem; /* 28px */"},
        {name: "6",     value: "right-6",     info: "right: 1.5rem; /* 24px */"},
        {name: "5",     value: "right-5",     info: "right: 1.25rem; /* 20px */"},
        {name: "4",     value: "right-4",     info: "right: 1rem; /* 16px */"},
        {name: "3.5",   value: "right-3.5",   info: "right: 0.875rem; /* 14px */"},
        {name: "3",     value: "right-3",     info: "right: 0.75rem; /* 12px */"},
        {name: "2.5",   value: "right-2.5",   info: "right: 0.625rem; /* 10px */"},
        {name: "2",     value: "right-2",     info: "right: 0.5rem; /* 8px */"},
        {name: "1.5",   value: "right-1.5",   info: "right: 0.375rem; /* 6px */"},
        {name: "1",     value: "right-1",     info: "right: 0.25rem; /* 4px */"},
        {name: "0.5",   value: "right-0.5",   info: "right: 0.125rem; /* 2px */"},
        {name: "px",    value: "right-px",    info: "right: 1px;"},

        {name: "-",     value: "",          info: "Default - No value"},
        {name: "0",     value: "right-0",     info: "right: 0px;"},

        {name: "-px",    value: "-right-px",    info: "right: -1px;"},
        {name: "-0.5",   value: "-right-0.5",   info: "right: -0.125rem; /* -2px */"},
        {name: "-1",     value: "-right-1",     info: "right: -0.25rem; /* -4px */"},
        {name: "-1.5",   value: "-right-1.5",   info: "right: -0.375rem; /* -6px */"},
        {name: "-2",     value: "-right-2",     info: "right: -0.5rem; /* -8px */"},
        {name: "-2.5",   value: "-right-2.5",   info: "right: -0.625rem; /* -10px */"},
        {name: "-3",     value: "-right-3",     info: "right: -0.75rem; /* -12px */"},
        {name: "-3.5",   value: "-right-3.5",   info: "right: -0.875rem; /* -14px */"},
        {name: "-4",     value: "-right-4",     info: "right: -1rem; /* -16px */"},
        {name: "-5",     value: "-right-5",     info: "right: -1.25rem; /* -20px */"},
        {name: "-6",     value: "-right-6",     info: "right: -1.5rem; /* -24px */"},
        {name: "-7",     value: "-right-7",     info: "right: -1.75rem; /* -28px */"},
        {name: "-8",     value: "-right-8",     info: "right: -2rem; /* -32px */"},
        {name: "-9",     value: "-right-9",     info: "right: -2.25rem; /* -36px */"},
        {name: "-10",    value: "-right-10",    info: "right: -2.5rem; /* -40px */"},
        {name: "-11",    value: "-right-11",    info: "right: -2.75rem; /* -44px */"},
        {name: "-12",    value: "-right-12",    info: "right: -3rem; /* -48px */"},
        {name: "-14",    value: "-right-14",    info: "right: -3.5rem; /* -56px */"},
        {name: "-16",    value: "-right-16",    info: "right: -4rem; /* -64px */"},
        {name: "-20",    value: "-right-20",    info: "right: -5rem; /* -80px */"},
        {name: "-24",    value: "-right-24",    info: "right: -6rem; /* -96px */"},
        {name: "-28",    value: "-right-28",    info: "right: -7rem; /* -112px */"},
        {name: "-32",    value: "-right-32",    info: "right: -8rem; /* -128px */"},
        {name: "-36",    value: "-right-36",    info: "right: -9rem; /* -144px */"},
        {name: "-40",    value: "-right-40",    info: "right: -10rem; /* -160px */"},
        {name: "-44",    value: "-right-44",    info: "right: -11rem; /* -176px */"},
        {name: "-48",    value: "-right-48",    info: "right: -12rem; /* -192px */"},
        {name: "-52",    value: "-right-52",    info: "right: -13rem; /* -208px */"},
        {name: "-56",    value: "-right-56",    info: "right: -14rem; /* -224px */"},
        {name: "-60",    value: "-right-60",    info: "right: -15rem; /* -240px */"},
        {name: "-64",    value: "-right-64",    info: "right: -16rem; /* -256px */"},
        {name: "-72",    value: "-right-72",    info: "right: -18rem; /* -288px */"},
        {name: "-80",    value: "-right-80",    info: "right: -20rem; /* -320px */"},
        {name: "-96",    value: "-right-96",    info: "right: -24rem; /* -384px */"},

        {name: "-auto",  value: "-right-auto",  info: "right: -auto;"},
        {name: "-1/2",   value: "-right-1/2",   info: "right: -50%;"},
        {name: "-1/3",   value: "-right-1/3",   info: "right: -33.333333%;"},
        {name: "-2/3",   value: "-right-2/3",   info: "right: -66.666667%;"},
        {name: "-1/4",   value: "-right-1/4",   info: "right: -25%;"},
        {name: "-2/4",   value: "-right-2/4",   info: "right: -50%;"},
        {name: "-3/4",   value: "-right-3/4",   info: "right: -75%;"},
        {name: "-full",  value: "-right-full",  info: "right: -100%;"},
    ];

    /**
     * Tailwind bottom- classes
     * @type Array<SelectOptions>
     */
    export let bottomClassOptions = [
        {name: "full",  value: "bottom-full",  info: "bottom: 100%;"},
        {name: "3/4",   value: "bottom-3/4",   info: "bottom: 75%;"},
        {name: "2/4",   value: "bottom-2/4",   info: "bottom: 50%;"},
        {name: "1/4",   value: "bottom-1/4",   info: "bottom: 25%;"},
        {name: "2/3",   value: "bottom-2/3",   info: "bottom: 66.666667%;"},
        {name: "1/3",   value: "bottom-1/3",   info: "bottom: 33.333333%;"},
        {name: "1/2",   value: "bottom-1/2",   info: "bottom: 50%;"},

        {name: "96",    value: "bottom-96",    info: "bottom: 24rem; /* 384px */"},
        {name: "80",    value: "bottom-80",    info: "bottom: 20rem; /* 320px */"},
        {name: "72",    value: "bottom-72",    info: "bottom: 18rem; /* 288px */"},
        {name: "64",    value: "bottom-64",    info: "bottom: 16rem; /* 256px */"},
        {name: "60",    value: "bottom-60",    info: "bottom: 15rem; /* 240px */"},
        {name: "56",    value: "bottom-56",    info: "bottom: 14rem; /* 224px */"},
        {name: "52",    value: "bottom-52",    info: "bottom: 13rem; /* 208px */"},
        {name: "48",    value: "bottom-48",    info: "bottom: 12rem; /* 192px */"},
        {name: "44",    value: "bottom-44",    info: "bottom: 11rem; /* 176px */"},
        {name: "40",    value: "bottom-40",    info: "bottom: 10rem; /* 160px */"},
        {name: "36",    value: "bottom-36",    info: "bottom: 9rem; /* 144px */"},
        {name: "32",    value: "bottom-32",    info: "bottom: 8rem; /* 128px */"},
        {name: "28",    value: "bottom-28",    info: "bottom: 7rem; /* 112px */"},
        {name: "24",    value: "bottom-24",    info: "bottom: 6rem; /* 96px */"},
        {name: "20",    value: "bottom-20",    info: "bottom: 5rem; /* 80px */"},
        {name: "16",    value: "bottom-16",    info: "bottom: 4rem; /* 64px */"},
        {name: "14",    value: "bottom-14",    info: "bottom: 3.5rem; /* 56px */"},
        {name: "12",    value: "bottom-12",    info: "bottom: 3rem; /* 48px */"},
        {name: "11",    value: "bottom-11",    info: "bottom: 2.75rem; /* 44px */"},
        {name: "10",    value: "bottom-10",    info: "bottom: 2.5rem; /* 40px */"},
        {name: "9",     value: "bottom-9",     info: "bottom: 2.25rem; /* 36px */"},
        {name: "8",     value: "bottom-8",     info: "bottom: 2rem; /* 32px */"},
        {name: "7",     value: "bottom-7",     info: "bottom: 1.75rem; /* 28px */"},
        {name: "6",     value: "bottom-6",     info: "bottom: 1.5rem; /* 24px */"},
        {name: "5",     value: "bottom-5",     info: "bottom: 1.25rem; /* 20px */"},
        {name: "4",     value: "bottom-4",     info: "bottom: 1rem; /* 16px */"},
        {name: "3.5",   value: "bottom-3.5",   info: "bottom: 0.875rem; /* 14px */"},
        {name: "3",     value: "bottom-3",     info: "bottom: 0.75rem; /* 12px */"},
        {name: "2.5",   value: "bottom-2.5",   info: "bottom: 0.625rem; /* 10px */"},
        {name: "2",     value: "bottom-2",     info: "bottom: 0.5rem; /* 8px */"},
        {name: "1.5",   value: "bottom-1.5",   info: "bottom: 0.375rem; /* 6px */"},
        {name: "1",     value: "bottom-1",     info: "bottom: 0.25rem; /* 4px */"},
        {name: "0.5",   value: "bottom-0.5",   info: "bottom: 0.125rem; /* 2px */"},
        {name: "px",    value: "bottom-px",    info: "bottom: 1px;"},

        {name: "-",     value: "",          info: "Default - No value"},
        {name: "0",     value: "bottom-0",     info: "bottom: 0px;"},

        {name: "-px",    value: "-bottom-px",    info: "bottom: -1px;"},
        {name: "-0.5",   value: "-bottom-0.5",   info: "bottom: -0.125rem; /* -2px */"},
        {name: "-1",     value: "-bottom-1",     info: "bottom: -0.25rem; /* -4px */"},
        {name: "-1.5",   value: "-bottom-1.5",   info: "bottom: -0.375rem; /* -6px */"},
        {name: "-2",     value: "-bottom-2",     info: "bottom: -0.5rem; /* -8px */"},
        {name: "-2.5",   value: "-bottom-2.5",   info: "bottom: -0.625rem; /* -10px */"},
        {name: "-3",     value: "-bottom-3",     info: "bottom: -0.75rem; /* -12px */"},
        {name: "-3.5",   value: "-bottom-3.5",   info: "bottom: -0.875rem; /* -14px */"},
        {name: "-4",     value: "-bottom-4",     info: "bottom: -1rem; /* -16px */"},
        {name: "-5",     value: "-bottom-5",     info: "bottom: -1.25rem; /* -20px */"},
        {name: "-6",     value: "-bottom-6",     info: "bottom: -1.5rem; /* -24px */"},
        {name: "-7",     value: "-bottom-7",     info: "bottom: -1.75rem; /* -28px */"},
        {name: "-8",     value: "-bottom-8",     info: "bottom: -2rem; /* -32px */"},
        {name: "-9",     value: "-bottom-9",     info: "bottom: -2.25rem; /* -36px */"},
        {name: "-10",    value: "-bottom-10",    info: "bottom: -2.5rem; /* -40px */"},
        {name: "-11",    value: "-bottom-11",    info: "bottom: -2.75rem; /* -44px */"},
        {name: "-12",    value: "-bottom-12",    info: "bottom: -3rem; /* -48px */"},
        {name: "-14",    value: "-bottom-14",    info: "bottom: -3.5rem; /* -56px */"},
        {name: "-16",    value: "-bottom-16",    info: "bottom: -4rem; /* -64px */"},
        {name: "-20",    value: "-bottom-20",    info: "bottom: -5rem; /* -80px */"},
        {name: "-24",    value: "-bottom-24",    info: "bottom: -6rem; /* -96px */"},
        {name: "-28",    value: "-bottom-28",    info: "bottom: -7rem; /* -112px */"},
        {name: "-32",    value: "-bottom-32",    info: "bottom: -8rem; /* -128px */"},
        {name: "-36",    value: "-bottom-36",    info: "bottom: -9rem; /* -144px */"},
        {name: "-40",    value: "-bottom-40",    info: "bottom: -10rem; /* -160px */"},
        {name: "-44",    value: "-bottom-44",    info: "bottom: -11rem; /* -176px */"},
        {name: "-48",    value: "-bottom-48",    info: "bottom: -12rem; /* -192px */"},
        {name: "-52",    value: "-bottom-52",    info: "bottom: -13rem; /* -208px */"},
        {name: "-56",    value: "-bottom-56",    info: "bottom: -14rem; /* -224px */"},
        {name: "-60",    value: "-bottom-60",    info: "bottom: -15rem; /* -240px */"},
        {name: "-64",    value: "-bottom-64",    info: "bottom: -16rem; /* -256px */"},
        {name: "-72",    value: "-bottom-72",    info: "bottom: -18rem; /* -288px */"},
        {name: "-80",    value: "-bottom-80",    info: "bottom: -20rem; /* -320px */"},
        {name: "-96",    value: "-bottom-96",    info: "bottom: -24rem; /* -384px */"},

        {name: "-auto",  value: "-bottom-auto",  info: "bottom: -auto;"},
        {name: "-1/2",   value: "-bottom-1/2",   info: "bottom: -50%;"},
        {name: "-1/3",   value: "-bottom-1/3",   info: "bottom: -33.333333%;"},
        {name: "-2/3",   value: "-bottom-2/3",   info: "bottom: -66.666667%;"},
        {name: "-1/4",   value: "-bottom-1/4",   info: "bottom: -25%;"},
        {name: "-2/4",   value: "-bottom-2/4",   info: "bottom: -50%;"},
        {name: "-3/4",   value: "-bottom-3/4",   info: "bottom: -75%;"},
        {name: "-full",  value: "-bottom-full",  info: "bottom: -100%;"},
    ];

    /**
     * Tailwind left- classes
     * @type Array<SelectOptions>
     */
    export let leftClassOptions = [
        {name: "full",  value: "left-full",  info: "left: 100%;"},
        {name: "3/4",   value: "left-3/4",   info: "left: 75%;"},
        {name: "2/4",   value: "left-2/4",   info: "left: 50%;"},
        {name: "1/4",   value: "left-1/4",   info: "left: 25%;"},
        {name: "2/3",   value: "left-2/3",   info: "left: 66.666667%;"},
        {name: "1/3",   value: "left-1/3",   info: "left: 33.333333%;"},
        {name: "1/2",   value: "left-1/2",   info: "left: 50%;"},

        {name: "96",    value: "left-96",    info: "left: 24rem; /* 384px */"},
        {name: "80",    value: "left-80",    info: "left: 20rem; /* 320px */"},
        {name: "72",    value: "left-72",    info: "left: 18rem; /* 288px */"},
        {name: "64",    value: "left-64",    info: "left: 16rem; /* 256px */"},
        {name: "60",    value: "left-60",    info: "left: 15rem; /* 240px */"},
        {name: "56",    value: "left-56",    info: "left: 14rem; /* 224px */"},
        {name: "52",    value: "left-52",    info: "left: 13rem; /* 208px */"},
        {name: "48",    value: "left-48",    info: "left: 12rem; /* 192px */"},
        {name: "44",    value: "left-44",    info: "left: 11rem; /* 176px */"},
        {name: "40",    value: "left-40",    info: "left: 10rem; /* 160px */"},
        {name: "36",    value: "left-36",    info: "left: 9rem; /* 144px */"},
        {name: "32",    value: "left-32",    info: "left: 8rem; /* 128px */"},
        {name: "28",    value: "left-28",    info: "left: 7rem; /* 112px */"},
        {name: "24",    value: "left-24",    info: "left: 6rem; /* 96px */"},
        {name: "20",    value: "left-20",    info: "left: 5rem; /* 80px */"},
        {name: "16",    value: "left-16",    info: "left: 4rem; /* 64px */"},
        {name: "14",    value: "left-14",    info: "left: 3.5rem; /* 56px */"},
        {name: "12",    value: "left-12",    info: "left: 3rem; /* 48px */"},
        {name: "11",    value: "left-11",    info: "left: 2.75rem; /* 44px */"},
        {name: "10",    value: "left-10",    info: "left: 2.5rem; /* 40px */"},
        {name: "9",     value: "left-9",     info: "left: 2.25rem; /* 36px */"},
        {name: "8",     value: "left-8",     info: "left: 2rem; /* 32px */"},
        {name: "7",     value: "left-7",     info: "left: 1.75rem; /* 28px */"},
        {name: "6",     value: "left-6",     info: "left: 1.5rem; /* 24px */"},
        {name: "5",     value: "left-5",     info: "left: 1.25rem; /* 20px */"},
        {name: "4",     value: "left-4",     info: "left: 1rem; /* 16px */"},
        {name: "3.5",   value: "left-3.5",   info: "left: 0.875rem; /* 14px */"},
        {name: "3",     value: "left-3",     info: "left: 0.75rem; /* 12px */"},
        {name: "2.5",   value: "left-2.5",   info: "left: 0.625rem; /* 10px */"},
        {name: "2",     value: "left-2",     info: "left: 0.5rem; /* 8px */"},
        {name: "1.5",   value: "left-1.5",   info: "left: 0.375rem; /* 6px */"},
        {name: "1",     value: "left-1",     info: "left: 0.25rem; /* 4px */"},
        {name: "0.5",   value: "left-0.5",   info: "left: 0.125rem; /* 2px */"},
        {name: "px",    value: "left-px",    info: "left: 1px;"},

        {name: "-",     value: "",          info: "Default - No value"},
        {name: "0",     value: "left-0",     info: "left: 0px;"},

        {name: "-px",    value: "-left-px",    info: "left: -1px;"},
        {name: "-0.5",   value: "-left-0.5",   info: "left: -0.125rem; /* -2px */"},
        {name: "-1",     value: "-left-1",     info: "left: -0.25rem; /* -4px */"},
        {name: "-1.5",   value: "-left-1.5",   info: "left: -0.375rem; /* -6px */"},
        {name: "-2",     value: "-left-2",     info: "left: -0.5rem; /* -8px */"},
        {name: "-2.5",   value: "-left-2.5",   info: "left: -0.625rem; /* -10px */"},
        {name: "-3",     value: "-left-3",     info: "left: -0.75rem; /* -12px */"},
        {name: "-3.5",   value: "-left-3.5",   info: "left: -0.875rem; /* -14px */"},
        {name: "-4",     value: "-left-4",     info: "left: -1rem; /* -16px */"},
        {name: "-5",     value: "-left-5",     info: "left: -1.25rem; /* -20px */"},
        {name: "-6",     value: "-left-6",     info: "left: -1.5rem; /* -24px */"},
        {name: "-7",     value: "-left-7",     info: "left: -1.75rem; /* -28px */"},
        {name: "-8",     value: "-left-8",     info: "left: -2rem; /* -32px */"},
        {name: "-9",     value: "-left-9",     info: "left: -2.25rem; /* -36px */"},
        {name: "-10",    value: "-left-10",    info: "left: -2.5rem; /* -40px */"},
        {name: "-11",    value: "-left-11",    info: "left: -2.75rem; /* -44px */"},
        {name: "-12",    value: "-left-12",    info: "left: -3rem; /* -48px */"},
        {name: "-14",    value: "-left-14",    info: "left: -3.5rem; /* -56px */"},
        {name: "-16",    value: "-left-16",    info: "left: -4rem; /* -64px */"},
        {name: "-20",    value: "-left-20",    info: "left: -5rem; /* -80px */"},
        {name: "-24",    value: "-left-24",    info: "left: -6rem; /* -96px */"},
        {name: "-28",    value: "-left-28",    info: "left: -7rem; /* -112px */"},
        {name: "-32",    value: "-left-32",    info: "left: -8rem; /* -128px */"},
        {name: "-36",    value: "-left-36",    info: "left: -9rem; /* -144px */"},
        {name: "-40",    value: "-left-40",    info: "left: -10rem; /* -160px */"},
        {name: "-44",    value: "-left-44",    info: "left: -11rem; /* -176px */"},
        {name: "-48",    value: "-left-48",    info: "left: -12rem; /* -192px */"},
        {name: "-52",    value: "-left-52",    info: "left: -13rem; /* -208px */"},
        {name: "-56",    value: "-left-56",    info: "left: -14rem; /* -224px */"},
        {name: "-60",    value: "-left-60",    info: "left: -15rem; /* -240px */"},
        {name: "-64",    value: "-left-64",    info: "left: -16rem; /* -256px */"},
        {name: "-72",    value: "-left-72",    info: "left: -18rem; /* -288px */"},
        {name: "-80",    value: "-left-80",    info: "left: -20rem; /* -320px */"},
        {name: "-96",    value: "-left-96",    info: "left: -24rem; /* -384px */"},

        {name: "-auto",  value: "-left-auto",  info: "left: -auto;"},
        {name: "-1/2",   value: "-left-1/2",   info: "left: -50%;"},
        {name: "-1/3",   value: "-left-1/3",   info: "left: -33.333333%;"},
        {name: "-2/3",   value: "-left-2/3",   info: "left: -66.666667%;"},
        {name: "-1/4",   value: "-left-1/4",   info: "left: -25%;"},
        {name: "-2/4",   value: "-left-2/4",   info: "left: -50%;"},
        {name: "-3/4",   value: "-left-3/4",   info: "left: -75%;"},
        {name: "-full",  value: "-left-full",  info: "left: -100%;"},
    ];



</script>

